/**
 * The Augsburg Confession (1530), word for word after the Book of Concord,
 * St. Louis 1881 (after the text of 1580), pp. 24–50: the preface and
 * Articles I–XXVII from the user's scan, Article XXVIII and the conclusion
 * from the scan at archive.org, checked against the Triglotta and the page.
 */
import { CONCORDIA } from './creeds';

export interface BookSection {
  id: string;
  title: string;
  sub: string;
  paragraphs: readonly string[];
}

export interface BookPart {
  heading?: string;
  sections: readonly BookSection[];
}

export const AUGSBURG_SOURCE = `${CONCORDIA}, S. 24–50.`;

export const AUGSBURG_CONFESSION: readonly BookPart[] = [
  {
    sections: [
      {
        id: 'vorrede',
        title: 'Vorrede',
        sub: '',
        paragraphs: [
          'Allerdurchlauchtigster, Großmächtigster, Unüberwindlichster Kaiser, Allergnädigster Herr! Als Eure Kaiserl. Majestät kurz verschienener Zeit einen gemeinen Reichstag allhier gen Augsburg gnädiglich ausgeschrieben, mit Anzeige und ernstem Begehr, von Sachen, unsern und des christlichen Namens Erbfeind, den Türken, betreffend, und wie demselben mit beharrlicher Hilfe stattlich widerstanden, auch wie der Zwiespalten halben in dem heiligen Glauben und der christlichen Religion gehandelt möge werden, zu rathschlagen und Fleiß anzukehren, alle eines jeglichen Gutbedünken, Opinion und Meinung zwischen uns selbst in Lieb und Gütigkeit zu hören, zu ersehen und zu erwägen, und dieselben zu einer einigen christlichen Wahrheit zu bringen und zu vergleichen, alles, so zu beiden Theilen nicht recht ausgelegt oder gehandelt wäre, abzuthun, und durch uns alle eine einige und wahre Religion anzunehmen und zu halten, und wie wir alle unter Einem Christo sind und streiten, also auch alle in Einer Gemeinschaft, Kirche und Einigkeit zu leben.',
          'Und wir, die unten benannten Churfürsten und Fürsten, sammt unsern Verwandten, gleich andern Churfürsten, Fürsten und Ständen, dazu erfordert, so haben wir uns darauf dermaßen erhaben, daß wir sonder Ruhm mit den ersten hieher gekommen.',
          'Und als denn auch E. K. M. zu unterthänigster Folgthuung berührtes E. K. M. Ausschreibens und demselbigen gemäß, dieser Sachen halben, den Glauben berührend, an Churfürsten, Fürsten und Stände ingemein gnädiglich, auch mit höchstem Fleiß und ernstlich begehrt, daß ein jeglicher, vermöge vorgemeldetes E. K. M. Ausschreibens, sein Gutbedünken, Opinion und Meinung derselbigen Irrungen, Zwiespalten und Mißbräuche halben etc. zu Deutsch und Latein in Schrift stellen und überantworten sollten; darauf denn, nach genommenem Bedacht und gehaltenem Rath, E. K. M. an vergangener Mittwochen ist vorgetragen worden, als wollten wir auf unserm Theil das Unsere, vermöge E. K. M. Vortrags, in Deutsch und Latein auf heut Freitag übergeben: hierum und E. K. M. zu unterthänigstem Gehorsam überreichen und übergeben wir unserer Pfarrherren, Prediger und ihrer Lehren, auch unsers Glaubens Bekenntniß, was und welcher Gestalt sie aus Grund göttlicher heiliger Schrift in unsern Landen, Fürstenthümern, Herrschaften, Städten und Gebieten predigen, lehren, halten und Unterricht thun.',
          'Und sind gegen E. K. M., unsern allergnädigsten Herrn, wir in aller Unterthänigkeit erbötig, so die andern Churfürsten, Fürsten und Stände dergleichen gezwiefachte schriftliche Uebergebung ihrer Meinung und Opinion in Latein und Deutsch jetzt auch thun werden, daß wir uns mit ihren Liebden und ihnen gern von bequemen gleichmäßigen Wegen unterreden und derselbigen, so viel der Gleichheit nach immer möglich vereinigen wollen, damit unser beiderseits, als Parten, schriftliches Vorbringen und Gebrechen zwischen uns selbst in Lieb und Gütigkeit gehandelt und dieselben Zwiespalten zu einer einigen wahren Religion, wie wir alle unter Einem Christo sind und streiten und Christum bekennen sollen, alles nach Laut oftgemeldetes E. K. M. Ausschreibens und nach göttlicher Wahrheit geführt mögen werden. Als wir denn auch Gott den Allmächtigen mit höchster Demuth anrufen und bitten wollen, seine göttliche Gnade dazu zu verleihen. Amen.',
          'Wo aber bei unsern Herren, Freunden, und besonders den Churfürsten, Fürsten und Ständen des andern Theils, die Handlung dermaßen, wie E. K. M. Ausschreiben vermag, unter uns selbst in Lieb und Gütigkeit bequeme Handlung nicht verfangen, noch ersprießlich sein wollte; als doch an uns in keinem, das mit Gott und Gewissen zu christlicher Einigkeit dienstlich sein kann oder mag, erwinden soll; wie E. K. M., auch gemeldete unsere Freunde, die Churfürsten, Fürsten, Stände, und ein jeder Liebhaber christlicher Religion, dem diese Sachen vorkommen, aus nachfolgenden unsern und der Unsern Bekenntnissen gnädiglich, freundlich und genugsam werden zu vernehmen haben. Nachdem denn E. K. M. vormals Churfürsten, Fürsten und Ständen des Reichs gnädiglich zu verstehen gegeben, und sonderlich durch eine öffentliche verlesene Instruction auf dem Reichstage, so im Jahr der mindern Zahl 26 zu Speyer gehalten, daß E. K. M. in Sachen, unsern heiligen Glauben belangend, zu schließen lassen, aus Ursachen, so dabei gemeldet, nicht gemeinet, sondern bei dem Pabst um ein Concilium fleißigen und Anhaltung thun wollten; und vor einem Jahr auf dem letzten Reichstag zu Speyer, vermöge einer schriftlichen Instruction, Churfürsten, Fürsten und Ständen des Reichs, durch E. K. M. Statthalter im Reich, Königliche Würden zu Ungarn und Böhmen etc. sammt E. K. M. Orator und verordneten Commissarien, dies unter andern haben vortragen und anzeigen lassen, daß E. K. M. derselbigen Statthalter, Amtsverwalter und Räthe des kaiserl. Regiments, auch der abwesenden Churfürsten, Fürsten und Stände Botschafter, so auf dem ausgeschriebenen Reichstag zu Regensburg versammelt gewesen, Gutbedünken, das Generalconcilium belangend, nachgedacht und solches anzusetzen auch für fruchtbar erkannt; und weil sich aber diese Sachen zwischen E. K. M. und dem Pabst zu gutem christlichem Verstand schicken, daß E. K. M. gewiß wäre, daß durch den Pabst das Generalconcilium zu halten nicht geweigert, so wäre E. K. M. gnädiges Erbietens, zu fordern und zu handeln, daß der Pabst solch Generalconcilium neben E. K. M. zum ersten auszuschreiben bewilligen, und daran kein Mangel erscheinen sollte.',
          'So erbieten gegen E. K. M. wir uns hiemit in aller Unterthänigkeit und zum Ueberfluß in berührtem Fall ferner auf ein solch gemein, frei, christlich Concilium, darauf auf allen Reichstagen, so E. K. M. bei ihrer Regierung im Reich gehalten, durch Churfürsten, Fürsten und Stände aus hohen und tapfern Bewegungen geschlossen, an welches auch zusammt E. K. M. wir uns von wegen dieser großwichtigsten Sache in rechtlicher Weise und Form verschienener Zeit berufen und appellirt haben, der wir hiemit nochmals anhängig bleiben und uns durch diese oder nachfolgende Handlung (es werden denn diese zwiespaltigen Sachen endlich in Lieb und Gütigkeit, laut E. K. M. Ausschreibens, gehört, erwogen, beigelegt und zu einer christlichen Einigkeit vergleichet) nicht zu begeben wissen, davon wir hiemit öffentlich bezeugen und protestiren. Und sind das unsere und der Unsern Bekenntnisse, wie unterschiedlich von Artikel zu Artikel hernach folget.',
        ],
      },
    ],
  },
  {
    heading: 'Artikel des Glaubens und der Lehre.',
    sections: [
      {
        id: 'art1',
        title: 'Der I. Artikel.',
        sub: 'Von Gott.',
        paragraphs: [
          'Erstlich wird einträchtiglich gelehrt und gehalten, laut des Beschlusses concilii Nicaeni, daß ein einig göttlich Wesen sei, welches genannt wird und wahrhaftiglich ist Gott, und sind doch drei Personen in demselbigen einigen göttlichen Wesen, gleich gewaltig, gleich ewig, Gott Vater, Gott Sohn, Gott Heiliger Geist, alle drei Ein göttlich Wesen, ewig, ohne Stück, ohne End, unermeßlicher Macht, Weisheit und Güte, ein Schöpfer und Erhalter aller sichtbaren und unsichtbaren Dinge. Und wird durch das Wort Persona verstanden nicht ein Stück, nicht eine Eigenschaft in einem andern, sondern das selbst bestehet; wie denn die Väter in dieser Sache dies Wort gebraucht haben.',
          'Derhalben werden verworfen alle Ketzereien, so diesem Artikel zuwider sind, als Manichäi, die zween Götter gesetzt haben, einen bösen und einen guten. Item Valentiniani, Ariani, Eunomiani, Mahometisten und alle dergleichen; auch Samosateni, alte und neue, so nur Eine Person setzen und von diesen zweien, Wort und Heiligem Geist, Sophisterei machen, und sagen, daß es nicht müssen unterschiedene Personen sein, sondern Wort bedeute leiblich Wort oder Stimme, und der Heilige Geist sei erschaffene Regung in Kreaturen.',
        ],
      },
      {
        id: 'art2',
        title: 'Der II. Artikel.',
        sub: 'Von der Erbsünde.',
        paragraphs: [
          'Weiter wird bei uns gelehrt, daß nach Adams Fall alle Menschen, so natürlich geboren werden, in Sünden empfangen und geboren werden, das ist, daß sie alle von Mutterleibe an voller böser Lust und Neigung sind und keine wahre Gottesfurcht, keinen wahren Glauben an Gott von Natur haben können; daß auch dieselbige angeborne Seuche und Erbsünde wahrhaftiglich Sünde sei, und verdamme alle die untern ewigen Gottes Zorn, so nicht durch die Taufe und Heiligen Geist wiederum neu geboren werden.',
          'Hieneben werden verworfen die Pelagianer und andere, so die Erbsünde nicht für Sünde haben, damit sie die Natur fromm machen durch natürliche Kräfte, zu Schmach dem Leiden und Verdienst Christi.',
        ],
      },
      {
        id: 'art3',
        title: 'Der III. Artikel.',
        sub: 'Von dem Sohne Gottes.',
        paragraphs: [
          'Item, es wird gelehrt, daß Gott der Sohn sei Mensch worden, geboren aus der reinen Jungfrau Maria, und daß die zwo Naturen, göttliche und menschliche, in Einer Person, also unzertrennlich vereinigt, Ein Christus sind, welcher wahrer Gott und Mensch ist, wahrhaftig geboren, gelitten, gekreuzigt, gestorben und begraben, daß er ein Opfer wäre nicht allein für die Erbsünde, sondern auch für alle anderen Sünden, und Gottes Zorn versöhnete.',
          'Item, daß derselbige Christus sei abgestiegen zur Hölle, wahrhaftig am dritten Tage von den Todten auferstanden, aufgefahren gen Himmel, sitzend zur Rechten Gottes, daß er ewig herrsche über alle Kreaturen und regiere, daß er alle, so an ihn glauben, durch den Heiligen Geist heilige, reinige, stärke und tröste, ihnen auch Leben und allerlei Gaben und Güter austheile, und wider den Teufel und wider die Sünde schütze und beschirme.',
          'Item, daß derselbige HErr Christus endlich wird öffentlich kommen, zu richten die Lebendigen und die Todten etc., laut des Symboli Apostolorum.',
        ],
      },
      {
        id: 'art4',
        title: 'Der IV. Artikel.',
        sub: 'Von der Rechtfertigung.',
        paragraphs: [
          'Weiter wird gelehrt, daß wir Vergebung der Sünden und Gerechtigkeit vor Gott nicht erlangen mögen durch unser Verdienst, Werk und Genugthun, sondern daß wir Vergebung der Sünden bekommen und vor Gott gerecht werden aus Gnaden um Christus willen durch den Glauben, so wir glauben, daß Christus für uns gelitten hat, und daß uns um seinetwillen die Sünden vergeben, Gerechtigkeit und ewiges Leben geschenkt wird. Denn diesen Glauben will Gott für Gerechtigkeit vor ihm halten und zurechnen, wie St. Paulus sagt zu den Römern am 3. und 4.',
        ],
      },
      {
        id: 'art5',
        title: 'Der V. Artikel.',
        sub: 'Vom Predigtamt.',
        paragraphs: [
          'Solchen Glauben zu erlangen, hat Gott das Predigtamt eingesetzt, Evangelium und Sacramente gegeben, dadurch er, als durch Mittel, den Heiligen Geist gibt, welcher den Glauben, wo und wann er will, in denen, so das Evangelium hören, wirkt, welches da lehret, daß wir durch Christus Verdienst, nicht durch unser Verdienst, einen gnädigen Gott haben, so wir solches glauben.',
          'Und werden verdammt die Wiedertäufer und andere, so lehren, daß wir ohne das leibliche Wort des Evangelii den Heiligen Geist durch eigene Bereitung, Gedanken und Werke erlangen.',
        ],
      },
      {
        id: 'art6',
        title: 'Der VI. Artikel.',
        sub: 'Vom neuen Gehorsam.',
        paragraphs: [
          'Auch wird gelehrt, daß solcher Glaube gute Früchte und gute Werke bringen soll, und daß man müsse gute Werke thun, allerlei, so Gott geboten hat, um Gottes willen, doch nicht auf solche Werke zu vertrauen, dadurch Gnade vor Gott zu verdienen; denn wir empfahen Vergebung der Sünden und Gerechtigkeit durch den Glauben an Christum, wie Christus selbst spricht, Luc. 17.: So ihr dies alles gethan habt, sollt ihr sprechen: wir sind untüchtige Knechte. Also lehren auch die Väter. Denn Ambrosius spricht: Also ists beschlossen bei Gott, daß, wer an Christum glaubt, selig sei, und nicht durch Werke, sondern allein durch den Glauben ohne Verdienst Vergebung der Sünden habe.',
        ],
      },
      {
        id: 'art7',
        title: 'Der VII. Artikel.',
        sub: 'Von der Kirche.',
        paragraphs: [
          'Es wird auch gelehrt, daß allezeit müsse Eine heilige christliche Kirche sein und bleiben, welche ist die Versammlung aller Gläubigen, bei welchen das Evangelium rein gepredigt und die heiligen Sacramente laut des Evangelii gereicht werden.',
          'Denn dieses ist genug zu wahrer Einigkeit der christlichen Kirche, daß da einträchtiglich nach reinem Verstand das Evangelium gepredigt und die Sacramente dem göttlichen Wort gemäß gereicht werden. Und ist nicht noth zu wahrer Einigkeit der christlichen Kirche, daß allenthalben gleichförmige Ceremonien, von den Menschen eingesetzt, gehalten werden; wie Paulus spricht Eph. 4, 5. 6.: Ein Leib, Ein Geist, wie ihr berufen seid zu einerlei Hoffnung eures Berufs, Ein HErr, Ein Glaube, Eine Taufe.',
        ],
      },
      {
        id: 'art8',
        title: 'Der VIII. Artikel.',
        sub: 'Was die Kirche sei.',
        paragraphs: [
          'Item, wiewohl die christliche Kirche eigentlich nichts anders ist, denn die Versammlung aller Gläubigen und Heiligen, jedoch dieweil in diesem Leben viel falscher Christen und Heuchler sind, auch öffentliche Sünder unter den Frommen bleiben, so sind die Sacramente gleichwohl kräftig, obschon die Priester, dadurch sie gereicht werden, nicht fromm sind; wie denn Christus selbst anzeigt Matth. 23, 2.: Auf dem Stuhl Moses sitzen die Pharisäer etc.',
          'Derhalben werden die Donatisten und alle andere verdammt, so anders halten.',
        ],
      },
      {
        id: 'art9',
        title: 'Der IX. Artikel.',
        sub: 'Von der Taufe.',
        paragraphs: [
          'Von der Taufe wird gelehrt, daß sie nöthig sei und daß dadurch Gnade angeboten werde, daß man auch die Kinder taufen soll, welche durch solche Taufe Gott überantwortet und gefällig werden.',
          'Derhalben werden die Wiedertäufer verworfen, welche lehren, daß die Kindertaufe nicht recht sei.',
        ],
      },
      {
        id: 'art10',
        title: 'Der X. Artikel.',
        sub: 'Vom heiligen Abendmahl.',
        paragraphs: [
          'Vom Abendmahl des HErrn wird also gelehrt, daß wahrer Leib und Blut Christi wahrhaftiglich unter der Gestalt des Brods und Weins im Abendmahl gegenwärtig sei und da ausgetheilt und genommen wird. Derhalben wird auch die Gegenlehre verworfen.',
        ],
      },
      {
        id: 'art11',
        title: 'Der XI. Artikel.',
        sub: 'Von der Beichte.',
        paragraphs: [
          'Von der Beichte wird also gelehrt, daß man in der Kirche privatam absolutionem erhalten und nicht fallen lassen soll; wiewohl in der Beichte nicht noth ist, alle Missethat und Sünden zu erzählen, dieweil doch solches nicht möglich ist, Ps. 19, 13.: Wer kennet die Missethat?',
        ],
      },
      {
        id: 'art12',
        title: 'Der XII. Artikel.',
        sub: 'Von der Buße.',
        paragraphs: [
          'Von der Buße wird gelehrt, daß diejenigen, so nach der Taufe gesündigt haben, zu aller Zeit, so sie zur Buße kommen, mögen Vergebung der Sünden erlangen, und ihnen die Absolution von der Kirche nicht soll geweigert werden; und ist wahre rechte Buße eigentlich Reu und Leid oder Schrecken haben über die Sünde, und doch daneben glauben an das Evangelium und Absolution, daß die Sünden vergeben und durch Christum Gnade erworben sei; welcher Glaube wiederum das Herz tröstet und zufrieden macht. Darnach soll auch Besserung folgen, und daß man von Sünden lasse; denn dies sollen die Früchte der Buße sein, wie Johannes spricht Matth. 3, 8.: Wirket rechtschaffene Früchte der Buße.',
          'Hie werden verworfen die, so lehren, daß diejenigen, so einst [d. i. einmal] sind fromm worden, nicht wieder fallen mögen.',
          'Dagegen werden auch verdammt die Novatiani, welche die Absolution denen, so nach der Taufe gesündigt hatten, weigerten.',
          'Auch werden die verworfen, so nicht lehren, daß man durch Glauben Vergebung der Sünden erlange, sondern durch unser Genugthun.',
        ],
      },
      {
        id: 'art13',
        title: 'Der XIII. Artikel.',
        sub: 'Vom Gebrauch der Sacramente.',
        paragraphs: [
          'Vom Brauch der Sacramente wird gelehrt, daß die Sacramente eingesetzt sind nicht allein darum, daß sie Zeichen seien, dabei man äußerlich die Christen kennen möge, sondern daß es Zeichen und Zeugnisse sind göttliches Willens gegen uns, unsern Glauben dadurch zu erwecken und zu stärken; derhalben sie auch Glauben fordern und dann recht gebraucht werden, so mans im Glauben empfähet und den Glauben dadurch stärket.',
        ],
      },
      {
        id: 'art14',
        title: 'Der XIV. Artikel.',
        sub: 'Vom Kirchen-Regiment.',
        paragraphs: [
          'Vom Kirchen-Regiment wird gelehrt, daß niemand in der Kirche öffentlich lehren oder predigen, oder Sacramente reichen soll ohne ordentlichen Beruf.',
        ],
      },
      {
        id: 'art15',
        title: 'Der XV. Artikel.',
        sub: 'Von Kirchen-Ordnungen.',
        paragraphs: [
          'Von Kirchen-Ordnungen, von Menschen gemacht, lehrt man diejenigen halten, so ohne Sünde mögen gehalten werden und zu Frieden, zu guter Ordnung in der Kirche dienen, als gewisse Feier, Festa und dergleichen. Doch geschieht Unterricht dabei, daß man die Gewissen nicht damit beschweren soll, als sei solch Ding nöthig zur Seligkeit. Darüber wird gelehrt, daß alle Satzungen und Traditionen, von Menschen dazu gemacht, daß man dadurch Gott versöhne und Gnade verdiene, dem Evangelio und der Lehre vom Glauben an Christum entgegen seien; derhalben seien Klostergelübde und andere Traditionen von Unterschied der Speise, Tage etc., dadurch man vermeint Gnade zu verdienen und für Sünden genug zu thun, untüchtig und wider das Evangelium.',
        ],
      },
      {
        id: 'art16',
        title: 'Der XVI. Artikel.',
        sub: 'Von Polizei und weltlichem Regiment.',
        paragraphs: [
          'Von Polizei und weltlichem Regiment wird gelehrt, daß alle Oberkeit in der Welt und geordnete Regimente und Gesetze gute Ordnung, von Gott geschaffen und eingesetzt sind; und daß Christen mögen in Oberkeit-, Fürsten- und Richteramt ohne Sünde sein, nach kaiserlichen und andern üblichen Rechten Urtheil und Recht sprechen, Uebelthäter mit dem Schwert strafen, rechte Kriege führen, streiten, kaufen und verkaufen, aufgelegte Eide thun, Eigenes haben, ehelich sein etc.',
          'Hie werden verdammt die Wiedertäufer, so lehren, daß der Obangezeigten keines christlich sei.',
          'Auch werden diejenigen verdammt, so lehren, daß christliche Vollkommenheit sei, Haus und Hof, Weib und Kind leiblich verlassen und sich der vorberührten Stücke äußern; so doch dies allein rechte Vollkommenheit ist: rechte Furcht Gottes und rechter Glaube an Gott; denn das Evangelium lehrt nicht ein äußerlich, zeitlich, sondern innerlich, ewig Wesen und Gerechtigkeit des Herzens, und stößt nicht um weltlich Regiment, Polizei und Ehestand, sondern will, daß man solches alles halte als wahrhaftige Ordnung, und in solchen Ständen christliche Liebe und rechte gute Werke, ein jeder nach seinem Beruf, beweise. Derhalben sind die Christen schuldig, der Oberkeit unterthan und ihren Geboten gehorsam zu sein in allem, so ohne Sünde geschehen mag; denn so der Oberkeit Gebot ohne Sünde nicht geschehen mag, soll man Gott mehr gehorsam sein, denn den Menschen. Actor. 5, 29.',
        ],
      },
      {
        id: 'art17',
        title: 'Der XVII. Artikel.',
        sub: 'Von der Wiederkunft Christi zum Gericht.',
        paragraphs: [
          'Auch wird gelehrt, daß unser HErr JEsus Christus am jüngsten Tage kommen wird, zu richten, und alle Todten auferwecken, den Gläubigen und Auserwählten ewiges Leben und ewige Freude geben, die gottlosen Menschen aber und die Teufel in die Hölle und ewige Strafe verdammen.',
          'Derhalben werden die Wiedertäufer verworfen, so lehren, daß die Teufel und verdammten Menschen nicht ewige Pein und Qual haben werden.',
          'Item, hie werden verworfen etliche jüdische Lehren, die sich auch jetzund ereignen, daß vor der Auferstehung der Todten eitel Heilige, Fromme ein weltlich Reich haben und alle Gottlosen vertilgen werden.',
        ],
      },
      {
        id: 'art18',
        title: 'Der XVIII. Artikel.',
        sub: 'Vom freien Willen.',
        paragraphs: [
          'Vom freien Willen wird gelehrt, daß der Mensch etlichermaßen einen freien Willen hat, äußerlich ehrbar zu leben und zu wählen unter den Dingen, so die Vernunft begreift; aber ohne Gnade, Hilfe und Wirkung des Heiligen Geistes vermag der Mensch nicht, Gott gefällig zu werden, Gott herzlich zu fürchten, oder zu glauben, oder die angeborne böse Lust aus dem Herzen zu werfen; sondern solches geschieht durch den Heiligen Geist, welcher durch Gottes Wort gegeben wird; denn Paulus spricht 1 Cor. 2, 14.: Der natürliche Mensch vernimmt nichts vom Geist Gottes.',
          'Und damit man erkennen möge, daß hierin keine Neuigkeit gelehrt werde, so sind das die klaren Worte Augustini vom freien Willen, wie jetzund hiebei geschrieben aus dem 3. Buch Hypognosticon: Wir bekennen, daß in allen Menschen ein freier Wille ist; denn sie haben je alle natürlichen, angebornen Verstand und Vernunft, nicht, daß sie etwas vermögen mit Gott zu handeln, als, Gott von Herzen zu lieben, zu fürchten; sondern allein in äußerlichen Werken dieses Lebens haben sie Freiheit, Gutes oder Böses zu wählen; Gutes, mein ich, das die Natur vermag, als, auf dem Acker zu arbeiten oder nicht, zu essen, zu trinken, zu einem Freunde zu gehen oder nicht, ein Kleid an oder auszuthun, zu bauen, ein Weib zu nehmen, ein Handwerk zu treiben und dergleichen etwas Nützliches und Gutes zu thun; welches alles doch ohne Gott nicht ist noch bestehet, sondern alles aus ihm und durch ihn ist. Dagegen kann der Mensch auch Böses aus eigener Wahl vornehmen, als, vor einem Abgott niederzuknieen, einen Todtschlag zu thun etc.',
        ],
      },
      {
        id: 'art19',
        title: 'Der XIX. Artikel.',
        sub: 'Von Ursach der Sünde.',
        paragraphs: [
          'Von Ursach der Sünde wird bei uns gelehrt, daß, wiewohl Gott der Allmächtige die ganze Natur geschaffen hat und erhält, so wirkt doch der verkehrte Wille die Sünde in allen Bösen und Verächtern Gottes; wie denn des Teufels Wille ist und aller Gottlosen, welcher alsbald, so Gott die Hand abgethan, sich von Gott zum Argen gewandt hat, wie Christus spricht Joh. 8, 44.: Der Teufel redet Lügen aus seinem Eigenen.',
        ],
      },
      {
        id: 'art20',
        title: 'Der XX. Artikel.',
        sub: 'Vom Glauben und guten Werken.',
        paragraphs: [
          'Den Unsern wird mit Unwahrheit aufgelegt, daß sie gute Werke verbieten; denn ihre Schriften von (den) zehen Geboten und andere beweisen, daß sie von rechten christlichen Ständen und Werken guten nützlichen Bericht und Ermahnung gethan haben, davon man vor dieser Zeit wenig gelehrt hat, sondern allermeist in allen Predigten auf kindische unnöthige Werke, als Rosenkränze, Heiligendienst, Mönchewerden, Wallfahrten, gesetzte Fasten, Feier, Brüderschaften etc. getrieben. Solche unnöthige Werke rühmet auch unser Widerpart nun nicht mehr so hoch als vor Zeiten; dazu haben sie auch gelernet nun vom Glauben zu reden, davon sie doch in Vorzeiten gar nichts gepredigt haben; lehren dennoch nun, daß wir nicht allein aus Werken gerecht werden vor Gott, sondern setzen den Glauben an Christum dazu, sprechen: Glaube und Werke machen uns gerecht vor Gott; welche Rede mehr Trosts bringen möge, denn so man allein lehrt auf Werke zu vertrauen.',
          'Dieweil nun die Lehre vom Glauben, die das Hauptstück ist in christlichem Wesen, so lange Zeit, wie man bekennen muß, nicht getrieben worden, sondern allein Werklehre an allen Orten gepredigt, ist davon durch die Unsern solcher Unterricht geschehen:',
          'Erstlich, daß uns unsere Werke nicht mögen mit Gott versöhnen und Gnade erwerben, sondern solches geschieht allein durch den Glauben, so man glaubt, daß uns um Christus willen die Sünden vergeben werden, welcher allein der Mittler ist, den Vater zu versöhnen. (1 Tim. 2, 5.) Wer nun vermeinet, solches durch Werke auszurichten und Gnade zu verdienen, der verachtet Christum und sucht einen eigenen Weg zu Gott, wider das Evangelium.',
          'Diese Lehre vom Glauben ist öffentlich und klar im Paulo an vielen Orten gehandelt, sonderlich zu den Ephesern am 2, 8.: Aus Gnaden seid ihr selig worden durch den Glauben, und dasselbige nicht aus euch, sondern es ist Gottes Gabe, nicht aus Werken, damit sich niemand rühme etc.',
          'Und daß hierin kein neuer Verstand eingeführt sei, kann man aus Augustino beweisen, der diese Sache fleißig handelt und auch also lehret, daß wir durch den Glauben an Christum Gnade erlangen und vor Gott gerecht werden, und nicht durch Werke, wie sein ganzes Buch de spiritu et litera ausweiset.',
          'Wiewohl nun diese Lehre bei unversuchten Leuten sehr verachtet wird, so befindet sich doch, daß sie den blöden und erschrockenen Gewissen sehr tröstlich und heilsam ist; denn das Gewissen kann nicht zu Ruhe und Friede kommen durch Werke, sondern allein durch Glauben, so es bei sich gewißlich schließt, daß es um Christus willen einen gnädigen Gott habe; wie auch Paulus spricht Röm. 5, 1.: So wir durch den Glauben sind gerecht worden, haben wir Ruhe und Friede mit Gott.',
          'Diesen Trost hat man vor Zeiten nicht getrieben in Predigten, sondern die armen Gewissen auf eigene Werke getrieben; und sind mancherlei Werke vorgenommen; denn Etliche hat das Gewissen in die Klöster gejagt, der Hoffnung, daselbst Gnade zu erwerben durch Klosterleben; Etliche haben andere Werke erdacht, damit Gnade zu verdienen und für die Sünden genug zu thun. Derselbigen viele haben erfahren, daß man dadurch nicht ist zu Frieden kommen. Darum ist noth gewesen, diese Lehre vom Glauben an Christum zu predigen und fleißig zu treiben, daß man wisse, daß man allein durch den Glauben, ohne Verdienst, Gottes Gnade ergreifet.',
          'Es geschieht auch Unterricht, daß man hie nicht von solchem Glauben redet, den auch die Teufel und Gottlosen haben, die auch die Historien glauben, daß Christus gelitten habe und auferstanden sei von Todten, sondern man redet von wahrem Glauben, der da glaubet, daß wir durch Christum Gnade und Vergebung der Sünden erlangen; und der nun weiß, daß er einen gnädigen Gott durch Christum hat, kennet also Gott, rufet ihn an und ist nicht ohne Gott wie die Heiden. Denn der Teufel und Gottlose glauben diesen Artikel, Vergebung der Sünden, nicht; darum sind sie Gott feind, können ihn nicht anrufen, nichts Gutes von ihm hoffen. Und also, wie jetzt angezeigt ist, redet die Schrift vom Glauben, und heißet nicht Glauben ein solches Wissen, das Teufel und gottlose Menschen haben; denn also wird vom Glauben gelehrt zu den Hebräern am 11., daß glauben sei nicht allein die Historien wissen, sondern Zuversicht haben zu Gott, seine Zusage zu empfahen. Und Augustinus erinnert uns auch, daß wir das Wort „Glaube“ in der Schrift verstehen sollen, daß es heiße Zuversicht zu Gott, daß er uns gnädig sei, und heiße nicht allein solche Historien wissen, wie auch die Teufel wissen.',
          'Ferner wird gelehrt, daß gute Werke sollen und müssen geschehen, nicht daß man darauf vertraue, Gnade damit zu verdienen, sondern um Gottes willen und Gott zu Lob. Der Glaube ergreift allezeit allein Gnade und Vergebung der Sünden. Und dieweil durch den Glauben der Heilige Geist gegeben wird, so wird auch das Herz geschickt, gute Werke zu thun. Denn zuvor, dieweil es ohne den Heiligen Geist ist, so ist es zu schwach; dazu ist es ins Teufels Gewalt, der die arme menschliche Natur zu viel Sünden treibt; wie wir sehen in den Philosophen, welche sich unterstanden, ehrlich und unsträflich zu leben, haben aber dennoch solches nicht ausgerichtet, sondern sind in viele große öffentliche Sünden gefallen. Also geht es mit dem Menschen, so er außer dem rechten Glauben ohne den Heiligen Geist ist und sich allein durch eigene menschliche Kräfte regiert.',
          'Derhalben ist die Lehre vom Glauben nicht zu schelten, daß sie gute Werke verbiete, sondern vielmehr zu rühmen, daß sie lehre gute Werke zu thun, und Hilfe anbiete, wie man zu guten Werken kommen möge. Denn außer dem Glauben und außerhalb Christo ist menschliche Natur und Vermögen viel zu schwach, gute Werke zu thun, Gott anzurufen, Geduld zu haben im Leiden, den Nächsten zu lieben, befohlene Aemter fleißig auszurichten, gehorsam zu sein, böse Lüste zu meiden. Solche hohe und rechte Werke mögen nicht geschehen ohne die Hilfe Christi; wie er selbst spricht Joh. 15, 5.: Ohne mich könnt ihr nichts thun etc.',
        ],
      },
      {
        id: 'art21',
        title: 'Der XXI. Artikel.',
        sub: 'Vom Dienst der Heiligen.',
        paragraphs: [
          'Vom Heiligen-Dienst wird von den Unsern also gelehrt, daß man der Heiligen gedenken soll, auf daß wir unsern Glauben stärken, so wir sehen, wie ihnen Gnade widerfahren, auch wie ihnen durch Glauben geholfen ist; dazu, daß man Exempel nehme von ihren guten Werken, ein jeder nach seinem Beruf, gleichwie die Kais. Majestät seliglich und göttlich dem Exempel David folgen mag, Kriege wider den Türken zu führen; denn beide sind sie in königlichem Amt, welches Schutz und Schirm ihrer Unterthanen fordert. Durch Schrift aber mag man nicht beweisen, daß man die Heiligen anrufen oder Hilfe bei ihnen suchen soll; denn es ist allein ein einiger Versöhner und Mittler gesetzt zwischen Gott und den Menschen, JEsus Christus, 1 Tim. 2, 5., welcher ist der einige Heiland, der einige oberste Priester, Gnadenstuhl und Fürsprecher vor Gott, Röm. 8, 34. Und der hat allein zugesagt, daß er unser Gebet erhören wolle. Das ist auch der höchste Gottesdienst nach der Schrift, daß man denselbigen JEsum Christum in allen Nöthen und Anliegen von Herzen suche und anrufe. 1 Joh. 2, 1.: So jemand sündigt, haben wir einen Fürsprecher bei Gott, der gerecht ist, JEsum.',
          'Dies ist fast die Summa der Lehre, welche in unsern Kirchen zu rechtem christlichem Unterricht und Trost der Gewissen, auch zu Besserung der Gläubigen gepredigt und gelehrt ist; wie wir denn unsere eigene Seele und Gewissen je nicht gerne wollten vor Gott mit Mißbrauch göttliches Namens oder Worts in die höchste und größte Fahr setzen, oder auf unsere Kinder und Nachkommen eine andere Lehre, denn so dem reinen göttlichen Wort und christlicher Wahrheit gemäß, fällen oder erben. So denn dieselbige in heiliger Schrift klar gegründet, und dazu auch gemeiner christlicher, ja römischer Kirche, so viel aus der Väter Schriften zu vermerken, nicht zuwider noch entgegen ist: so achten wir auch, unsere Widersacher können in obangezeigten Artikeln nicht uneinig mit uns sein. Derhalben handeln diejenigen ganz unfreundlich, geschwind und wider alle christliche Einigkeit und Liebe, so die Unsern derhalben als Ketzer abzusondern, zu verwerfen und zu meiden ihnen selbst ohne einigen beständigen Grund göttlicher Gebote oder Schrift vornehmen. Denn die Irrung und Zank ist vornehmlich über etlichen Traditionen und Mißbräuchen. So denn nun an den Hauptartikeln kein befindlicher Ungrund oder Mangel, und dies unser Bekenntniß göttlich und christlich ist, sollten sich billig die Bischöfe, wenn schon bei uns der Tradition halben ein Mangel wäre, gelinder erzeigen; wiewohl wir verhoffen, beständigen Grund und Ursachen darzuthun, warum bei uns etliche Traditionen und Mißbräuche geändert sind.',
        ],
      },
    ],
  },
  {
    heading: 'Artikel, von welchen Zwiespalt ist, da erzählt werden die Mißbräuche, so geändert sind.',
    sections: [
      {
        id: 'abusus',
        title: 'Eingang',
        sub: '',
        paragraphs: [
          'So nun von den Artikeln des Glaubens in unsern Kirchen nicht gelehrt wird zuwider der heiligen Schrift, oder gemeiner christlicher Kirche, sondern allein etliche Mißbräuche geändert sind, welche zum Theil mit der Zeit selbst eingerissen, zum Theil mit Gewalt aufgerichtet, fordert unsere Nothdurft, dieselbigen zu erzählen und Ursache darzuthun, warum hierin Aenderung geduldet ist; damit Kais. Majestät erkennen möge, daß nicht hierin unchristlich oder freventlich gehandelt, sondern daß wir durch Gottes Gebot, welches billig höher zu achten, denn alle Gewohnheit, gedrungen sind, solche Aenderung zu gestatten.',
        ],
      },
      {
        id: 'art22',
        title: 'Der XXII. Artikel.',
        sub: 'Von beider Gestalt des Sacraments.',
        paragraphs: [
          'Den Laien wird bei uns beide Gestalt des Sacraments gereicht aus dieser Ursache, daß dies ist ein klarer Befehl und Gebot Christi, Matth. 26.: Trinket alle daraus. Da gebeut Christus mit klaren Worten von dem Kelch, daß sie alle daraus trinken sollen.',
          'Und damit niemand diese Worte anfechten und glossiren könne, als gehöre es allein den Priestern zu, so zeigt Paulus 1 Cor. 11, 26. an, daß die ganze Versammlung der Corinther Kirchen beide Gestalt gebraucht hat. Und dieser Brauch ist lange Zeit in der Kirche geblieben, wie man durch die Historien und der Väter Schriften beweisen kann. Cyprianus gedenkt an viel Orten, daß den Laien der Kelch die Zeit gereicht sei. So spricht St. Hieronymus, daß die Priester, so das Sacrament reichen, dem Volk das Blut Christi austheilen. So gebeut Gelasius, der Pabst, selbst, daß man das Sacrament nicht theilen soll, distinct. 2. de consecrat. c. Comperimus. Man findet auch nindert (nirgend) keinen Canon, der da gebiete, allein Eine Gestalt zu nehmen. Es kann auch niemand wissen, wann oder durch welche diese Gewohnheit, Eine Gestalt zu nehmen, eingeführt ist; wiewohl der Cardinal Cusanus gedenkt, wann diese Weise approbirt sei. Nun ists öffentlich, daß solche Gewohnheit, wider Gottes Gebot, auch wider die alten Canones eingeführt, unrecht ist. Derhalben hat sich nicht gebühret, derjenigen Gewissen, so das heilige Sacrament nach Christus Einsetzung zu gebrauchen begehrt haben, zu beschweren und zu zwingen, wider unsers HErrn Christi Ordnung zu handeln. Und dieweil die Theilung des Sacraments der Einsetzung Christi zu entgegen ist, wird auch bei uns die gewöhnliche Procession mit dem Sacrament unterlassen.',
        ],
      },
      {
        id: 'art23',
        title: 'Der XXIII. Artikel.',
        sub: 'Vom Ehestand der Priester.',
        paragraphs: [
          'Es ist bei jedermann, hohes und niederes Standes, eine große mächtige Klage in der Welt gewesen von großer Unzucht und wildem Wesen und Leben der Priester, so nicht vermochten Keuschheit zu halten, und war auch je mit solchen greulichen Lastern aufs höchste gekommen. So viel häßliches, großes Aergerniß, Ehebruch und andere Unzucht zu vermeiden, haben sich etliche Priester bei uns in ehelichen Stand begeben. Dieselben zeigen an diese Ursachen, daß sie dahin gedrungen und bewegt sind aus hoher Noth ihrer Gewissen, nachdem die Schrift klar meldet, der eheliche Stand sei von Gott dem HErrn eingesetzt, Unzucht zu vermeiden, wie Paulus sagt 1 Cor. 7, 2.: Die Unzucht zu vermeiden, hab ein jeglicher sein eigen Eheweib, item: Es ist besser ehelich werden, denn brennen. Und nachdem Christus sagt Matth. 19, 12.: Sie fassen nicht alle das Wort, da zeigt Christus an (welcher wohl gewußt hat, was am Menschen sei), daß wenig Leute die Gabe keusch zu leben haben, denn Gott hat den Menschen Männlein und Fräulein geschaffen, Gen. 1, 28. Ob es nun in menschlicher Macht oder Vermögen sei, ohne sonderliche Gabe und Gnade Gottes durch eigen Vornehmen oder Gelübde Gottes der hohen Majestät Geschöpfe besser zu machen oder zu ändern, hat die Erfahrung allzuklar gegeben; denn was Gutes, was ehrbares, züchtiges Lebens, was christliches, ehrliches oder redliches Wandels an vielen daraus erfolget, wie greuliche, schreckliche Unruhe und Qual ihrer Gewissen viele an ihrem letzten Ende derhalben gehabt, ist am Tage, und ihrer viele haben es selbst bekennet. So denn Gottes Wort und Gebot durch kein menschlich Gelübde oder Gesetz mag geändert werden, haben aus dieser und andern Ursachen und Gründen die Priester und andere Geistliche Eheweiber genommen.',
          'So es ist auch aus den Historien und der Väter Schriften zu beweisen, daß in der christlichen Kirche vor Alters der Brauch gewesen, daß die Priester und Diakonen Eheweiber gehabt; darum sagt Paulus 1 Tim. 3, 2.: Es soll ein Bischof unsträflich sein, Eines Weibes Mann. Es sind auch in Deutschland erst vor vierhundert Jahren die Priester zum Gelübde der Keuschheit vom Ehestand mit Gewalt abgedrungen, welche sich dagegen sämmtlich, auch so ganz ernstlich und hart gesetzt haben, daß ein Erzbischof zu Mainz, welcher das päbstliche neue Edict derhalben verkündigt, gar nahe in einer Empörung der ganzen Priesterschaft in einem Gedränge wäre umgebracht. Und dasselbige Verbot ist bald im Anfang so geschwind und unschicklich vorgenommen, daß der Pabst die Zeit nicht allein die künftige Ehe den Priestern verboten, sondern auch Derjenigen Ehe, so schon in dem Stand lange gewesen, zerrissen; welches doch nicht allein wider alle göttliche, natürliche und weltliche Rechte, sondern auch den Canonibus (so die Päbste selbst gemacht) und den berühmtesten Conciliis ganz entgegen und zuwider ist.',
          'Auch ist bei viel hohen, gottfürchtigen, verständigen Leuten dergleichen Rede und Bedenken oft gehört, daß solcher gedrungener Cölibat und Beraubung des Ehestandes (welchen Gott selbst eingesetzt und frei gelassen) nie kein Gutes, sondern viel großer böser Laster und viel Arges eingeführt habe. Es hat auch einer von den Päbsten, Pius II., selbst, wie seine Historie anzeigt, diese Worte oft geredet und von sich schreiben lassen: es möge wohl etliche Ursachen haben, warum den Geistlichen die Ehe verboten sei; es habe aber viel höhere, größere und wichtigere Ursachen, warum man ihnen die Ehe soll wieder frei lassen. Ungezweifelt, es hat Pabst Pius, als ein verständiger, weiser Mann, dies Wort aus großem Bedenken geredet.',
          'Derhalben wollen wir uns in Unterthänigkeit zu Kaiserl. Majestät vertrösten, daß Ihre Majestät als ein christlicher hochlöblicher Kaiser gnädiglich beherzigen werde, daß jetzund in letzten Zeiten und Tagen, von welchen die Schrift meldet, die Welt immer je ärger und die Menschen gebrechlicher und schwächer werden.',
          'Derhalben wohl hochnöthig, nützlich und christlich ist, diese fleißige Einsehung zu thun, damit, wo der Ehestand verboten, nicht ärgere und schändlichere Unzucht und Laster in deutschen Landen möchten einreißen. Denn es wird je diese Sache niemand weislicher oder besser ändern oder machen können, denn Gott selbst, welcher den Ehestand, menschlicher Gebrechlichkeit zu helfen und Unzucht zu wehren, eingesetzt hat.',
          'So sagen die alten Canones auch, man müsse zu Zeiten die Schärfe und rigorem lindern und nachlassen, um menschlicher Schwachheit willen und Aergeres zu verhüten und zu meiden.',
          'Nun wäre das in diesem Fall auch wohl christlich und ganz hoch vonnöthen. Was kann auch der Priester und der Geistlichen Ehestand gemeiner christlicher Kirche nachtheilig sein, sonderlich der Pfarrherrn und anderer, die der Kirche dienen sollen? Es würde wohl künftig an Priestern und Pfarrherrn mangeln, so dies harte Verbot des Ehestands länger währen sollte.',
          'So nun dieses, nämlich daß die Priester und Geistlichen mögen ehelich werden, gegründet ist auf das göttliche Wort und Gebot; dazu die Historien beweisen, daß die Priester ehelich gewesen; so auch das Gelübde der Keuschheit so viel häßliche, unchristliche Aergernisse, so viel Ehebruch, schreckliche, ungehörte Unzucht und greuliche Laster hat angerichtet, daß auch etliche unter den Thumherren, Curtisanen zu Rom solches oft selbst bekennet und kläglich angezogen, wie solche Laster im Clero zu greulich und übermacht, Gottes Zorn würde erregt werden: so ists je erbärmlich, daß man den christlichen Ehestand nicht allein verboten, sondern an etlichen Orten aufs geschwindeste, wie um groß Uebelthat, zu strafen unterstanden hat. So ist auch der Ehestand in kaiserlichen Rechten und in allen Monarchien, wo je Gesetz und Recht gewesen, hoch gelobet. Allein dieser Zeit beginnt man die Leute unschuldig allein um der Ehe willen zu martern, und dazu Priester, deren man vor Andern schonen sollte; und geschieht nicht allein wider göttliche Rechte, sondern auch wider die Canones. Paulus der Apostel 1 Tim. 4, 1. ff. nennt die Lehren, so die Ehe verbieten, Teufels-Lehren. So sagt Christus selbst Joh. 8, 44.: Der Teufel sei ein Mörder von Anbeginn. Welches denn wohl zusammenstimmt, daß es freilich Teufels-Lehren sein müssen, die Ehe verbieten, und sich unterstehen, solche Lehre mit Blutvergießen zu erhalten.',
          'Wie aber kein menschlich Gesetz Gottes Gebot kann wegthun oder ändern, also kann auch kein Gelübde Gottes Gebot ändern. Darum gibt auch St. Cyprianus den Rath, daß die Weiber, so die gelobte Keuschheit nicht halten, sollen ehelich werden, und sagt l. 1. epist. 11. also: So sie aber Keuschheit nicht halten wollen oder nicht vermögen, so ists besser, daß sie ehelich werden, denn daß sie durch ihre Lust ins Feuer fallen, und sollen sich wohl vorsehen, daß sie den Brüdern und Schwestern kein Aergerniß anrichten.',
          'Zudem, so brauchen auch alle Canones größere Gelindigkeit und Aequität gegen diejenigen, so in der Jugend Gelübde gethan; wie denn Priester und Mönche des mehreren Theils in der Jugend in solchen Stand aus Unwissenheit gekommen sind.',
        ],
      },
      {
        id: 'art24',
        title: 'Der XXIV. Artikel.',
        sub: 'Von der Messe.',
        paragraphs: [
          'Man legt den Unsern mit Unrecht auf, daß sie die Messe sollen abgethan haben. Denn das ist öffentlich, daß die Messe, ohne Ruhm zu reden, bei uns mit größerer Andacht und Ernst gehalten wird, denn bei den Widersachern. So werden auch die Leute mit höchstem Fleiß zum öftern mal unterrichtet vom heiligen Sacrament, wozu es eingesetzt und wie es zu gebrauchen sei, als nämlich die erschrockenen Gewissen damit zu trösten, dadurch das Volk zur Communion und Messe gezogen wird. Dabei geschieht auch Unterricht wider andere unrechte Lehre vom Sacrament. So ist auch in den öffentlichen Ceremonien der Messe keine merkliche Aenderung geschehen, denn daß an etlichen Orten deutsche Gesänge (das Volk damit zu lehren und zu üben) neben lateinischem Gesang gesungen werden; sintemal alle Ceremonien vornehmlich dazu dienen sollen, daß das Volk daran lerne, was ihm zu wissen von Christo noth ist.',
          'Nachdem aber die Messe auf mancherlei Weise vor dieser Zeit gemißbraucht, wie am Tage ist, daß ein Jahrmarkt daraus gemacht, daß man sie gekauft und verkauft hat und das mehrere Theil in allen Kirchen um Geldes willen gehalten worden, ist solcher Mißbrauch zu mehrmalen, auch vor dieser Zeit, von gelehrten und frommen Leuten gestraft worden. Als nun die Prediger bei uns davon gepredigt und die Priester erinnert sind der schrecklichen Bedräuung (so denn billig einen jeden Christen bewegen soll), daß wer das Sacrament unwürdiglich braucht, der sei schuldig am Leib und Blut Christi, darauf sind solche Kaufmessen und Winkelmessen (welche bis anher aus Zwang um Geldes und der Präbenden willen gehalten worden) in unsern Kirchen gefallen.',
          'Dabei ist auch der greuliche Irrthum gestraft, daß man gelehrt hat, unser HErr Christus habe durch seinen Tod allein für die Erbsünde genug gethan und die Messe eingesetzt zu einem Opfer für die andern Sünden, und also die Messe zu einem Opfer gemacht für die Lebendigen und Todten, dadurch Sünden wegzunehmen und Gott zu versöhnen. Daraus ist weiter gefolgt, daß man disputirt hat, ob eine Messe, für viele gehalten, also viel verdiene, als so man für einen jeglichen eine sonderliche hielte. Daher ist die große unzählige Menge der Messen gekommen, daß man mit diesem Werk hat wollen bei Gott alles erlangen, das man bedurft hat, und ist daneben des Glaubens an Christum und rechten Gottesdienstes vergessen worden.',
          'Darum ist davon Unterricht geschehen, wie ohne Zweifel die Noth gefordert, daß man wüßte, wie das Sacrament recht zu gebrauchen wäre. Und erstlich, daß kein Opfer für Erbsünde und andere Sünde sei, denn der einige Tod Christi, zeigt die Schrift an vielen Orten an. Denn also steht geschrieben zu den Hebräern, daß sich Christus einmal geopfert hat, und dadurch für alle Sünden genug gethan. Es ist eine unerhörte Neuigkeit, in der Kirche lehren, daß Christus Tod sollte allein für die Erbsünde, und sonst nicht auch für andere Sünden, genug gethan haben; derhalben zu hoffen, daß männiglich verstehe, daß solcher Irrthum nicht unbillig gestraft sei.',
          'Zum andern, so lehrt St. Paulus, daß wir vor Gott Gnade erlangen durch Glauben und nicht durch Werke. Dawider ist öffentlich dieser Mißbrauch der Messe, so man vermeinet, durch dieses Werk Gnade zu erlangen, wie man denn weiß, daß man die Messe dazu gebraucht, dadurch Sünde abzulegen und Gnade und alle Güter bei Gott zu erlangen, nicht allein der Priester für sich, sondern auch für die ganze Welt und für Andere, Lebendige und Todte.',
          'Zum dritten, so ist das heilige Sacrament eingesetzt, nicht damit für die Sünde ein Opfer anzurichten (denn das Opfer ist zuvor geschehen), sondern daß unser Glaube dadurch erweckt und die Gewissen getröstet werden, welche durchs Sacrament erinnert werden, daß ihnen Gnade und Vergebung der Sünde von Christo zugesagt ist. Derhalben fordert dies Sacrament Glauben und wird ohne Glauben vergeblich gebraucht.',
          'Dieweil nun die Messe nicht ein Opfer ist für Andere, Lebendige oder Todte, ihre Sünden wegzunehmen, sondern soll eine Communion sein, da der Priester und Andere das Sacrament empfahen für sich: so wird diese Weise bei uns gehalten, daß man an Feiertagen, auch sonst, so Communicanten da sind, Messe hält und etliche, so das begehren, communicirt. Also bleibt die Messe bei uns in ihrem rechten Brauch, wie sie vor Zeiten in der Kirche gehalten, wie man beweisen mag aus St. Paulo 1 Cor. 11., dazu auch vieler Väter Schriften; denn Chrysostomus spricht, wie der Priester täglich stehe und fordere Etliche zur Communion, Etlichen verbiete er hinzu zu treten. Auch zeigen die alten Canones an, daß einer das Amt gehalten hat und die andern Priester und Diakonen communicirt. Denn also lauten die Worte im canone Nicaeno: Die Diakonen sollen nach den Priestern ordentlich das Sacrament empfahen vom Bischof oder Priester.',
          'So man nun keine Neuigkeit hierin, die in der Kirche vor Alters nicht gewesen, vorgenommen hat, und in den öffentlichen Ceremonien der Messe keine merkliche Aenderung geschehen ist, allein daß die andern unnöthigen Messen, etwa durch einen Mißbrauch gehalten neben der Pfarrmesse, gefallen sind: soll billig diese Weise, Messe zu halten, nicht für ketzerisch und unchristlich verdammt werden. Denn man hat vor Zeiten auch in den großen Kirchen, da viel Volks gewesen, auch auf die Tage, so das Volk zusammen kam, nicht täglich Messe gehalten; wie tripartita historia lib. 9. anzeigt, daß man zu Alexandria am Mittwoch und Freitag die Schrift gelesen und ausgelegt habe, und sonst alle Gottesdienste gehalten ohne die Messe.',
        ],
      },
      {
        id: 'art25',
        title: 'Der XXV. Artikel.',
        sub: 'Von der Beichte.',
        paragraphs: [
          'Die Beichte ist durch die Prediger dieses Theils nicht abgethan; denn diese Gewohnheit wird bei uns gehalten, das Sacrament nicht zu reichen denen, so nicht zuvor verhört und absolvirt sind. Dabei wird das Volk fleißig unterrichtet, wie tröstlich das Wort der Absolution sei, wie hoch und theuer die Absolution zu achten; denn es sei nicht des gegenwärtigen Menschen Stimme oder Wort, sondern Gottes Wort, der da die Sünde vergibt; denn sie wird an Gottes Statt und aus Gottes Befehl gesprochen. Von diesem Befehl und Gewalt der Schlüssel, wie tröstlich, wie nöthig sie sei den erschrockenen Gewissen, wird mit großem Fleiß gelehrt; dazu, wie Gott fordert, dieser Absolution zu glauben, nicht weniger, denn so Gottes Stimme vom Himmel erschölle, und uns dero fröhlich trösten, und wissen, daß wir durch solchen Glauben Vergebung der Sünden erlangen. Von diesen nöthigen Stücken haben vor Zeiten die Prediger, so von der Beichte viel lehrten, nicht ein Wörtlein gerührt, sondern allein die Gewissen gemartert mit langer Erzählung der Sünden, mit Genugthun, mit Ablaß, mit Wallfahrten und dergleichen. Und viele unserer Widersacher bekennen selbst, daß dieses Theils von rechter christlicher Buße schicklicher, denn zuvor in langer Zeit, geschrieben und gehandelt sei.',
          'Und wird von der Beichte also gelehrt, daß man niemand dringen solle, die Sünden namhaftig zu erzählen; denn solches ist unmöglich, wie der Psalm (19, 13.) spricht: Wer kennet die Missethat? Und Jeremias 17, 9. spricht: Des Menschen Herz ist so arg, daß man es nicht auslernen kann. Die elende menschliche Natur steckt also tief in Sünden, daß sie dieselben nicht alle sehen oder kennen kann, und sollten wir allein von denen absolvirt werden, die wir zählen können, wäre uns wenig geholfen. Derhalben ist nicht noth, die Leute zu dringen, die Sünden namhaftig zu erzählen. Also haben auch die Väter gehalten, wie man findet distinct. 1. de poenitentia, da die Worte Chrysostomi angezogen werden: Ich sage nicht, daß du dich selbst sollst öffentlich dargeben, noch bei einem andern dich selbst verklagen oder schuldig geben, sondern gehorche dem Propheten, welcher spricht: Offenbare dem HErrn deine Wege, Ps. 37, 5. Derhalben beichte Gott dem HErrn, dem wahrhaftigen Richter, neben deinem Gebet; nicht sage deine Sünden mit der Zunge, sondern in deinem Gewissen. Hie sieht man klar, daß Chrysostomus nicht zwingt, die Sünden namhaftig zu erzählen. So lehrt auch die glossa in decretis, de poenitentia, distinct. 5. cap. Consideret, daß die Beichte nicht durch die Schrift geboten, sondern durch die Kirche eingesetzt sei. Doch wird durch die Prediger dieses Theils fleißig gelehrt, daß die Beichte von wegen der Absolution, welche das Hauptstück und das Vornehmste darin ist, zu Trost der erschrockenen Gewissen, dazu um etlicher anderer Ursachen willen zu erhalten sei.',
        ],
      },
      {
        id: 'art26',
        title: 'Der XXVI. Artikel.',
        sub: 'Vom Unterschied der Speisen.',
        paragraphs: [
          'Vor Zeiten hat man also gelehrt, gepredigt und geschrieben, daß Unterschied der Speisen und dergleichen Traditionen, von Menschen eingesetzt, dazu dienen, daß man dadurch Gnade verdiene und für die Sünde genugthue. Aus diesem Grunde hat man täglich neue Fasten, neue Ceremonien, neue Orden und dergleichen erdacht, und auf solches heftig und hart getrieben, als seien solche Dinge nöthige Gottesdienste, dadurch man Gnade verdiene, so mans halte, und große Sünde geschehe, so mans nicht halte. Daraus sind viel schädlicher Irrthümer in der Kirche erfolgt.',
          'Erstlich, ist dadurch die Gnade Christi und die Lehre vom Glauben verdunkelt, welche uns das Evangelium mit großem Ernst vorhält, und treibt hart darauf, daß man das Verdienst Christi hoch und theuer achte, und wisse, daß glauben an Christum hoch und weit über alle Werke zu setzen sei. Derhalben hat St. Paulus heftig wider das Gesetz Mosis und menschliche Traditiones gefochten, daß wir lernen sollen, daß wir vor Gott nicht fromm werden aus unsern Werken, sondern allein durch den Glauben an Christum, daß wir Gnade erlangen um Christus willen; solche Lehre ist schier ganz verloschen, dadurch, daß man gelehrt, Gnade zu verdienen mit Gesetzen, Fasten, Unterschied der Speisen, Kleidern etc.',
          'Zum andern, haben auch solche Traditiones Gottes Gebot verdunkelt; denn man setzt diese Traditiones weit über Gottes Gebot. Dies hielt man allein für christliches Leben, wer die Feier also hielt, also betete, also fastete, also gekleidet war; das nannte man geistliches, christliches Leben.',
          'Daneben hielt man andere nöthige gute Werke für ein weltliches ungeistliches Wesen, nämlich diese, so jeder nach seinem Beruf zu thun schuldig ist; als, daß der Hausvater arbeitet, Weib und Kind zu ernähren und zu Gottesfurcht aufzuziehen, die Hausmutter Kinder gebiert und wartet ihrer, ein Fürst und Obrigkeit Land und Leute regiert etc. Solche Werke, von Gott geboten, mußten ein weltliches und unvollkommenes Wesen sein, aber die Traditiones mußten den prächtigen Namen haben, daß sie allein heilige, vollkommene Werke hießen. Derhalben war kein Maß noch Ende, solche Traditiones zu machen.',
          'Zum dritten, solche Traditiones sind zu hoher Beschwerung der Gewissen gerathen. Denn es war nicht möglich, alle Traditiones zu halten, und waren doch die Leute in der Meinung, als wäre solches ein nöthiger Gottesdienst, und schreibt Gerson, daß Viele hiemit in Verzweiflung gefallen, Etliche haben sich auch selbst umgebracht, derhalben, daß sie keinen Trost von der Gnade Christi gehört haben. Denn man sieht bei den Summisten und Theologen, wie die Gewissen verwirrt, welche sich unterstanden haben, die Traditiones zusammen zu ziehen, und ἐπιεικείας [epieikeias] gesucht, daß sie den Gewissen hülfen, haben so viel damit zu thun gehabt, daß dieweil alle heilsame christliche Lehre von nöthigeren Sachen, als vom Glauben, vom Trost in hohen Anfechtungen und dergleichen, danieder gelegen ist. Darüber haben auch viel frommer Leute vor dieser Zeit sehr geklagt, daß solche Traditiones viel Zanks in der Kirche anrichten, und daß fromme Leute, damit verhindert, zu rechtem Erkenntniß Christi nicht kommen möchten. Gerson und etliche mehr haben heftig darüber geklagt. Ja, es hat auch Augustino mißfallen, daß man die Gewissen mit so viel Traditionibus beschweret. Derhalben er dabei Unterricht gibt, daß mans nicht für nöthige Dinge halten soll.',
          'Darum haben die Unsern nicht aus Frevel oder Verachtung geistlicher Gewalt von diesen Sachen gelehrt, sondern es hat die hohe Noth gefordert, Unterricht zu thun von obangezeigten Irrthümern, welche aus Mißverstand der Traditionen gewachsen sind. Denn das Evangelium zwingt, daß man die Lehre vom Glauben solle und müsse in Kirchen treiben, welche doch nicht mag verstanden werden, so man vermeint, durch eigene erwählte Werke Gnade zu verdienen.',
          'Und ist also davon gelehrt, daß man durch Haltung gedachter menschlicher Traditionen nicht kann Gnade verdienen, oder Gott versöhnen, oder für die Sünde genug thun; und soll derhalben kein nöthiger Gottesdienst daraus gemacht werden. Dazu wird Ursach aus der Schrift angezogen. Christus Matth. 15, 3. 9. entschuldigt die Apostel, daß sie gewöhnliche Traditiones nicht gehalten haben, und spricht dabei: Sie ehren mich vergeblich mit Menschengeboten. So er nun dies einen vergeblichen Dienst nennet, muß er nicht nöthig sein. Und bald hernach: Was zum Munde eingehet, verunreiniget den Menschen nicht. Item Paulus spricht Röm 14, 17.: Das Himmelreich stehet nicht in Speise oder Trank; Col. 2, 16.: Niemand soll euch richten in Speise, Trank, Sabbath etc. Act. 15, 10. spricht Petrus: Warum versucht ihr Gott mit Auflegung des Jochs auf der Jünger Hälse, welches weder unsere Väter noch wir haben mögen tragen? Sondern wir glauben durch die Gnade unsers HErrn JEsu Christi selig zu werden. Da verbeut Petrus, daß man die Gewissen nicht beschweren soll mit mehr äußerlichen Ceremonien, es sei Mosis oder andern. Und 1 Tim. 4, 1—3. werden solche Verbote, als, Speise verbieten, Ehe verbieten etc., Teufelslehre genennet. Denn dies ist stracks dem Evangelio entgegen, solche Werke einsetzen oder thun, daß man damit Vergebung der Sünden verdiene, oder als möge niemand Christen sein ohne solche Dienste.',
          'Daß man aber den Unsern hie Schuld gibt, als verbieten sie Kasteiung und Zucht, wie Jovinianus, wird sich viel anders aus ihren Schriften befinden; denn sie haben allezeit gelehrt vom heiligen Kreuz, daß Christen zu leiden schuldig sind; und dieses ist rechte, ernstliche und nicht erdichtete Kasteiung.',
          'Daneben wird auch gelehrt, daß ein jeglicher schuldig ist, sich mit leiblicher Uebung, als Fasten und andere Uebung, also zu halten, daß er nicht Ursache zu Sünden gebe, nicht, daß er mit solchen Werken Gnade verdiene. Diese leibliche Uebung soll nicht allein etliche bestimmte Tage, sondern stetigs getrieben werden. Davon redet Christus (Luc. 21, 34.): Hütet euch, daß eure Herzen nicht beschweret werden mit Völlerei; item (Matth. 17, 21.): Die Teufel werden nicht ausgeworfen, denn durch Fasten und Gebet. Und Paulus spricht (1 Cor. 9, 27.), er kasteie seinen Leib und bringe ihn zu Gehorsam; damit er anzeigt, daß Kasteiung dienen soll, nicht damit Gnade zu verdienen, sondern den Leib geschickt zu halten, daß er nicht verhindere, was einem jeglichen nach seinem Beruf zu schaffen befohlen ist. Und wird also nicht das Fasten verworfen, sondern daß man einen nöthigen Dienst daraus auf bestimmte Tage und Speisen zu Verwirrung der Gewissen gemacht hat.',
          'Auch werden dieses Theils viel Ceremonien und Traditionen gehalten, als, Ordnung der Messe und andere Gesänge, Feste etc., welche dazu dienen, daß in der Kirche Ordnung gehalten werde. Daneben aber wird das Volk unterrichtet, daß solcher äußerlicher Gottesdienst nicht fromm macht vor Gott, und daß mans ohne Beschwerung des Gewissens halten soll, also, daß, so man es nachläßt ohne Aergerniß, nicht daran gesündigt wird. Diese Freiheit in äußerlichen Ceremonien haben auch die alten Väter gehalten; denn im Orient hat man das Osterfest auf andere Zeit, denn zu Rom, gehalten. Und da etliche diese Ungleichheit für eine Trennung in der Kirche halten wollten, sind sie vermahnet von andern, daß nicht noth ist, in solchen Gewohnheiten Gleichheit zu halten. Und spricht Irenäus also: Ungleichheit im Fasten trennet nicht die Einigkeit des Glaubens. Wie auch distinct. 12. von solcher Ungleichheit in menschlichen Ordnungen geschrieben, daß sie der Einigkeit der Christenheit nicht zuwider sei. Und tripartita hist. lib. 9. zeucht zusammen viel ungleicher Kirchengewohnheiten und setzt einen nützlichen christlichen Spruch: Der Apostel Meinung ist nicht gewesen, Feiertage einzusetzen, sondern Glaube und Liebe zu lehren.',
        ],
      },
      {
        id: 'art27',
        title: 'Der XXVII. Artikel.',
        sub: 'Von Klostergelübden.',
        paragraphs: [
          'Von Klostergelübden zu reden ist noth, erstlich zu bedenken, wie es bis anher damit gehalten, welch Wesen sie in Klöstern gehabt, und daß sehr viel darin täglich nicht allein wider Gottes Wort, sondern auch päbstlichen Rechten zu entgegen gehandelt ist. Denn zu St. Augustini Zeiten sind Klosterstände frei gewesen; folgend, da die rechte Zucht und Lehre zerrüttet, hat man Klostergelübde erdacht, und damit eben als mit einem erdachten Gefängniß die Zucht wiederum aufrichten wollen.',
          'Ueber das hat man neben den Klostergelübden viel andere Stücke mehr aufgebracht, und mit solchen Banden und Beschwerden ihrer viel, auch vor gebührenden Jahren, beladen.',
          'So sind auch viel Personen aus Unwissenheit zu solchem Klosterleben gekommen, welche, wiewohl sie sonst nicht zu jung gewesen, haben doch ihr Vermögen nicht genugsam ermessen und verstanden; dieselben alle, also verstrickt und verwickelt, sind gezwungen und gedrungen, in solchen Banden zu bleiben, ungeachtet dessen, daß auch päbstisch Recht ihrer viel frei gibt. Und das ist beschwerlicher gewesen in Jungfrauenklöstern, denn Mönchsklöstern; so sich doch geziemet hätte, der Weibsbilder als der Schwachen zu verschonen. Dieselbe Strenge und Härtigkeit hat auch viel frommen Leuten in Vorzeiten mißfallen; denn sie haben wohl gesehen, daß beide, Knaben und Maidlein, um Erhaltung willen des Leibes in die Klöster sind versteckt worden. Sie haben auch wohl gesehen, wie übel dasselbe Vornehmen gerathen ist, was Aergerniß, was Beschwerung der Gewissen es gebracht, und haben viel Leute geklagt, daß man in solcher gefährlichen Sache die Canones so gar nicht geachtet. Zudem, so hat man eine solche Meinung von den Klostergelübden, die unverborgen auch viel Mönchen übel gefallen hat, die (ein) wenig einen Verstand gehabt.',
          'Denn sie gaben vor, daß Klostergelübde der Taufe gleich wären und daß man mit dem Klosterleben Vergebung der Sünden und Rechtfertigung vor Gott verdienete; ja, sie setzen noch mehr dazu, daß man mit dem Klosterleben verdienete nicht allein Gerechtigkeit und Frommkeit, sondern auch, daß man damit hielte die Gebote und Räthe, im Evangelio verfaßt, und wurden also die Klostergelübde höher gepreiset, denn die Taufe. Item, daß man mehr verdienete mit dem Klosterleben, denn mit allen andern Ständen, so von Gott geordnet sind, als Pfarrherr- und Predigerstand, Obrigkeit-, Fürsten-, Herrenstand und dergleichen, die alle nach Gottes Gebot, Wort und Befehl in ihrem Beruf ohne erdichtete Geistlichkeit dienen; wie denn dieser Stücke keines verneint werden mag, denn man findets in ihren eigenen Büchern. Ueber das, wer also gefangen und ins Kloster gekommen, lernte wenig von Christo.',
          'Etwa hat man Schulen der heiligen Schrift und anderer Künste, so der christlichen Kirche dienstlich sind, in den Klöstern gehalten, daß man aus den Klöstern Pfarrherren und Bischöfe genommen hat; jetzt aber hats viel eine andere Gestalt; denn vor Zeiten kamen sie der Meinung zusammen im Klosterleben, daß man die Schrift lernete; jetzt geben sie vor, das Klosterleben sei ein solch Wesen, daß man Gottes Gnade und Frommkeit vor Gott damit verdiene, ja, es sei ein Stand der Vollkommenheit, und setzens den andern Ständen, so von Gott eingesetzt, weit vor. Das alles wird darum angezogen, ohne alle Verunglimpfung, damit man je desto baß vernehmen und verstehen möge, was und wie die Unsern predigen und lehren.',
          'Erstlich lehren sie bei uns von denen, die zur Ehe greifen, also, daß alle die, so zum ledigen Stand nicht geschickt sind, Macht, Fug und Recht haben, sich zu verehelichen; denn die Gelübde vermögen nicht, Gottes Ordnung und Gebot aufzuheben. Nun lautet Gottes Gebot also 1 Cor. 7, 2.: Um der Hurerei willen habe ein jeglicher sein eigen Weib, und eine jegliche habe ihren eigenen Mann. Dazu dringet, zwinget und treibet nicht allein Gottes Gebot, sondern auch Gottes Geschöpf und Ordnung, alle die zum Ehestand, die ohne sonderes Gottes Werk mit der Gabe der Jungfrauschaft nicht begnadet sind, laut dieses Spruchs Gottes selbst Gen. 2, 18.: Es ist nicht gut, daß der Mensch allein sei, wir wollen ihm einen Gehilfen machen, der um ihn sei.',
          'Was mag man nun dawider aufbringen? Man rühme das Gelübde und Pflicht, wie hoch man wolle, man mutze es auf, als hoch man kann, so mag man dennoch nicht erzwingen, daß Gottes Gebot dadurch aufgehoben werde. Die Doctores sagen, daß die Gelübde, auch wider des Pabsts Recht, unbündig sind, wie viel weniger sollen sie denn binden, Statt und Kraft haben wider Gottes Gebot!',
          'Wo die Pflichten der Gelübde keine andere Ursachen hätten, daß sie möchten aufgehoben werden, so hätten die Päbste auch nicht dawider dispensirt oder erlaubt; denn es gebühret keinem Menschen, die Pflicht, so aus göttlichen Rechten herwächst, zu zerreißen. Darum haben die Päbste wohl bedacht, daß in dieser Pflicht eine Aequität soll gebraucht werden, und haben zum öfternmal dispensirt; als mit einem Könige von Aragon und vielen andern. So man nun zu Erhaltung zeitlicher Dinge dispensirt hat, soll viel billiger dispensirt werden um Nothdurft willen der Seelen.',
          'Folgends, warum treibt der Gegentheil so hart, daß man die Gelübde halten muß, und siehet nicht zuvor an, ob das Gelübde seine Art habe? Denn das Gelübde soll in möglichen Sachen, willig und ungezwungen sein. Wie aber die ewige Keuschheit in des Menschen Gewalt und Vermögen stehe, weiß man wohl; auch sind wenig, beide Manns- und Weibspersonen, die von ihnen selbst, willig und wohl bedacht das Klostergelübde gethan haben. Ehe sie zum rechten Verstand kommen, so überredet man sie zum Klostergelübde; zuweilen werden sie auch dazu gezwungen und gedrungen. Darum ist es je nicht billig, daß man so geschwind und hart von der Gelübdpflicht disputire, angesehen, daß sie alle bekennen, daß solches wider die Natur und Art des Gelübdes ist, daß es nicht williglich und mit gutem Rath und Bedacht gelobet wird.',
          'Etliche Canones und päbstliche Rechte zerreißen die Gelübde, die unter fünfzehn Jahren geschehen sind; denn sie haltens dafür, daß man vor derselben Zeit so viel Verstandes nicht hat, daß man die Ordnung des ganzen Lebens, wie dasselbe anzustellen, beschließen könne.',
          'Ein anderer Canon gibt der menschlichen Schwachheit noch mehr Jahre zu; denn er verbeut, das Klostergelübde unter achtzehn Jahren zu thun; daraus hat der meiste Theil Entschuldigung und Ursachen, aus den Klöstern zu gehen, denn sie des mehrern Theils in der Kindheit vor diesen Jahren in Klöster gekommen sind. Endlich, wenn gleich die Verbrechung des Klostergelübdes möchte getadelt werden, so könnte aber dennoch nicht daraus erfolgen, daß man Derselben Ehe zerreißen sollte. Denn St. Augustinus sagt 27. q. 1. cap. Nuptiarum, daß man solche Ehe nicht zerreißen soll. Nun ist je St. Augustin nicht in geringem Ansehen in der christlichen Kirche, obgleich etliche hernach anders gehalten.',
          'Wiewohl nun Gottes Gebot von dem Ehestande ihrer sehr viele vom Klostergelübde frei und ledig gemacht, so wenden doch die Unsern noch mehr Ursachen vor, daß Klostergelübde nichtig und unbündig seien; denn aller Gottesdienst, von den Menschen ohne Gottes Gebot und Befehl eingesetzt und erwählet, Gerechtigkeit und Gottes Gnade zu erlangen, sei wider Gott und dem Evangelio und Gottes Befehl entgegen; wie denn Christus selbst sagt Matth. 15, 9.: Sie dienen mir vergebens mit Menschengeboten. So lehrets auch St. Paulus überall, daß man Gerechtigkeit nicht soll suchen aus unsern Geboten und Gottesdiensten, so von Menschen erdichtet sind, sondern daß Gerechtigkeit und Frommkeit vor Gott kommt aus dem Glauben und Vertrauen, daß wir glauben, daß uns Gott um seines einigen Sohnes Christus willen zu Gnaden annimmt. Nun ist es je am Tage, daß die Mönche gelehrt und gepredigt haben, daß die erdachte Geistlichkeit genug thue für die Sünde und Gottes Gnade und Gerechtigkeit erlange. Was ist nun dies anders, denn die Herrlichkeit und Preis der Gnade Christi vermindern und die Gerechtigkeit des Glaubens verleugnen? Darum folgt aus dem, daß solche gewöhnliche Gelübde unrechte, falsche Gottesdienste gewesen. Derhalben sind sie auch unbündig; denn ein gottlos Gelübde, und das wider Gottes Gebot geschehen, ist unbündig und nichtig; wie auch die Canones lehren, daß der Eid nicht soll ein Band zur Sünde sein.',
          'St. Paulus sagt zu den Galatern am 5, 4.: Ihr seid ab von Christo, die ihr durch das Gesetz rechtfertig werden wollt, und habt der Gnade gefehlet. Derhalben auch die, so durch Gelübde wollen rechtfertig werden, sind von Christo ab und fehlen der Gnade Gottes; denn dieselben rauben Christo seine Ehre, der allein gerecht macht, und geben solche Ehre ihren Gelübden und Klosterleben.',
          'Man kann auch nicht leugnen, daß die Mönche gelehrt und gepredigt haben, daß sie durch ihre Gelübde und Klosterwesen und Weise gerecht werden und Vergebung der Sünden verdienen; ja, sie haben noch wohl ungeschickter Ding erdichtet und gesagt, daß sie ihre guten Werke den andern mittheilen. Wenn nun einer dies alles wollte unglimpflich treiben und aufmutzen: wie viel Stücke könnte er zusammenbringen, deren sich die Mönche jetzt selbst schämen und nicht wollen gethan haben! Ueber das alles haben sie auch die Leute überredet, daß die erdichteten geistlichen Ordensstände sind christliche Vollkommenheit; dies ist ja die Werke rühmen, daß man dadurch gerecht werde. Nun ist es nicht ein geringes Aergerniß in der christlichen Kirche, daß man dem Volke einen solchen Gottesdienst vorträgt, den die Menschen ohne Gottes Gebot erdichtet haben, und lehren, daß ein solcher Gottesdienst die Menschen vor Gott fromm und gerecht macht. Denn Gerechtigkeit des Glaubens, die man am meisten in der Kirche treiben soll, wird verdunkelt, wenn den Leuten die Augen aufgesperrt werden mit dieser seltsamen Engelsgeistlichkeit und falschem Vorgeben der Armuth, Demuth und Keuschheit.',
          'Ueber das werden auch die Gebote Gottes und der rechte und wahre Gottesdienst dadurch verdunkelt, wenn die Leute hören, daß allein die Mönche im Stande der Vollkommenheit sein sollen. Denn die christliche Vollkommenheit ist, daß man Gott von Herzen und mit Ernst fürchtet, und doch auch eine herzliche Zuversicht und Glauben, auch Vertrauen fasset, daß wir um Christus willen einen gnädigen barmherzigen Gott haben, daß wir mögen und sollen von Gott bitten und begehren, was uns noth ist, und Hilfe von ihm in allen Trübsalen gewißlich nach eines jeden Beruf und Stand gewarten; daß wir auch indeß sollen äußerlich mit Fleiß gute Werke thun und unsers Berufs warten. Darin steht die rechte Vollkommenheit und der rechte Gottesdienst, nicht im Betteln oder in einer schwarzen oder grauen Kappe etc. Aber das gemeine Volk faßt viel schädlicher Meinungen aus falschem Lob des Klosterlebens, so sie es hören, daß man den ledigen Stand ohne alle Maß lobt; folget, daß es mit beschwertem Gewissen im Ehestand ist; denn daraus, so der gemeine Mann hört, daß die Bettler allein sollen vollkommen sein, kann er nicht wissen, daß er ohne Sünde Güter haben und hantieren möge. So das Volk höret, es sei nur ein Rath, nicht Rache üben, folgt, daß etliche vermeinen, es sei nicht Sünde, außerhalb des Amtes Rache zu üben. Etliche meinen, Rache gezieme den Christen gar nicht, auch nicht der Oberkeit. Man liest auch der Exempel viel, daß etliche Weib und Kind, auch ihr Regiment verlassen und sich in Klöster gesteckt haben. Dasselbe, haben sie gesagt, heißt aus der Welt fliehen und ein solch Leben suchen, das Gott baß gefiele, denn der Andern Leben. Sie haben auch nicht können wissen, daß man Gott dienen soll in den Geboten, die Er gegeben hat, und nicht in den Geboten, die von Menschen erdichtet sind. Nun ist je das ein guter und vollkommener Stand des Lebens, welcher Gottes Gebot für sich hat; das aber ist ein fährlicher Stand des Lebens, der Gottes Gebot nicht für sich hat.',
          'Von solchen Sachen ist vonnöthen gewesen, den Leuten guten Bericht zu thun. Es hat auch Gerson in Vorzeiten den Irrthum der Mönche von der Vollkommenheit gestraft, und zieht an, daß bei seinen Zeiten dieses eine neue Rede gewesen sei, daß das Klosterleben ein Stand der Vollkommenheit sein soll. So viel gottloser Meinungen und Irrthümer kleben in den Klostergelübden: daß sie sollen rechtfertigen und fromm vor Gott machen, daß sie die christliche Vollkommenheit sein sollen, daß man damit beide, des Evangelions Räthe und Gebote, halte, daß sie haben die Uebermaß der Werke, die man Gott nicht schuldig sei. Dieweil denn solches alles falsch, eitel und erdichtet ist, so macht es auch die Klostergelübde nichtig und unbündig.',
        ],
      },
      {
        id: 'art28',
        title: 'Der XXVIII. Artikel.',
        sub: 'Von der Bischöfe Gewalt.',
        paragraphs: [
          'Von der Bischöfe Gewalt ist vor Zeiten viel und mancherlei geschrieben und haben etliche ungeschicklich die Gewalt der Bischöfe und das weltliche Schwert untereinander gemengt, und sind aus diesem unordentlichen Gemenge sehr große Kriege, Aufruhr und Empörungen erfolget, aus dem daß die Bischöfe im Schein ihrer Gewalt, die ihnen von Christo gegeben, nicht allein neue Gottesdienste angerichtet haben und mit Vorbehaltung etlicher Fälle und mit gewaltsamem Bann die Gewissen beschwert, sondern auch sich unterwunden, Kaiser und Könige zu setzen und entsetzen ihres Gefallens; welchen Frevel auch lange Zeit hievor gelehrte und gottfürchtige Leute in der Christenheit gestraft haben. Derhalben die Unsern zu Trost der Gewissen gezwungen sind worden, den Unterschied der geistlichen und weltlichen Gewalt, Schwerts und Regiments anzuzeigen, und haben gelehrt, daß man beide Regimente und Gewalten um Gottes Gebots willen mit aller Andacht ehren und wohl halten soll als zwo höchste Gaben Gottes auf Erden.',
          'Nun lehren die Unsern also, daß die Gewalt der Schlüssel oder der Bischöfe sei, laut des Evangelions, eine Gewalt und Befehl Gottes, das Evangelium zu predigen, die Sünde zu vergeben und zu behalten, und die Sacramente zu reichen und zu handeln. Denn Christus hat die Apostel mit dem Befehl ausgesandt (Joh. 20, 21. ff.): Gleichwie mich mein Vater gesandt hat, also sende ich euch auch. Nehmet hin den Heiligen Geist; welchen ihr die Sünden erlassen werdet, denen sollen sie erlassen sein, und denen ihr sie vorbehalten werdet, denen sollen sie vorbehalten sein.',
          'Dieselbe Gewalt der Schlüssel oder Bischöfe übt und treibet man allein mit der Lehre und Predigt Gottes Worts und mit Handreichung der Sacramente gegen viele oder einzelne Personen, darnach der Beruf ist. Denn damit werden gegeben nicht leibliche, sondern ewige Dinge und Güter, als nämlich, ewige Gerechtigkeit, der Heilige Geist und das ewige Leben. Diese Güter kann man anders nicht erlangen, denn durch das Amt der Predigt und durch die Handreichung der heiligen Sacramente. Denn St. Paulus spricht (Röm. 1, 16.): Das Evangelium ist eine Kraft Gottes, selig zu machen alle, die daran glauben. Dieweil nun die Gewalt der Kirche oder Bischöfe ewige Güter gibt und allein durch das Predigtamt geübt und getrieben wird, so hindert sie die Polizei und das weltliche Regiment nichts überall. Denn das weltliche Regiment gehet mit viel andern Sachen um, denn das Evangelium; welche Gewalt schützt nicht die Seelen, sondern Leib und Gut wider äußerliche Gewalt mit dem Schwert und leiblichen Pönen.',
          'Darum soll man die zwei Regimente, das geistliche und weltliche, nicht in einander mengen und werfen; denn die geistliche Gewalt hat ihren Befehl, das Evangelium zu predigen und die Sacramente zu reichen, soll auch nicht in ein fremd Amt fallen, soll nicht Könige setzen oder entsetzen, soll weltlich Gesetz und Gehorsam der Oberkeit nicht aufheben oder zerrütten, soll weltlicher Gewalt nicht Gesetze machen und stellen von weltlichen Händeln; wie denn auch Christus selbst gesagt hat (Joh. 18, 36.): Mein Reich ist nicht von dieser Welt; item (Luc. 12, 14.): Wer hat mich zu einem Richter zwischen euch gesetzt? Und St. Paulus zu den Philippern am 3, 20.: Unsere Bürgerschaft ist im Himmel; und in der zweiten zu den Corinthern 10, 4.: Die Waffen unserer Ritterschaft sind nicht fleischlich, sondern mächtig vor Gott, zu verstören die Anschläge und alle Höhe, die sich erhebt wider die Erkenntniß Gottes. Dieser Gestalt unterscheiden die Unsern beider Regimente und Gewalte Amt, und heißen sie beide als die höchste Gabe Gottes auf Erden in Ehren halten. Wo aber die Bischöfe weltlich Regiment und Schwert haben, so haben sie dieselben nicht als Bischöfe aus göttlichen Rechten, sondern aus menschlichen kaiserlichen Rechten, geschenkt von Kaisern und Königen zu weltlicher Verwaltung ihrer Güter, und gehet das Amt des Evangelions gar nichts an.',
          'Derhalben ist das bischöfliche Amt nach göttlichen Rechten: das Evangelium predigen, Sünden vergeben, Lehre urtheilen, und die Lehre, so dem Evangelio entgegen, verwerfen, und die Gottlosen, dero gottlos Wesen offenbar ist, aus christlicher Gemeine ausschließen, ohne menschliche Gewalt, sondern allein durch Gottes Wort. Und diesfalls sind die Pfarrleute und Kirchen schuldig, den Bischöfen gehorsam zu sein, laut dieses Spruchs Christi, Luc. am 10, 16.: Wer euch höret, der höret mich. Wo sie aber etwas dem Evangelio entgegen lehren, setzen oder aufrichten, haben wir Gottes Befehl in solchem Fall, daß wir nicht sollen gehorsam sein, Matth. am 7, 15.: Sehet euch vor vor den falschen Propheten. Und St. Paulus zu den Galatern am 1, 8.: So auch wir oder ein Engel vom Himmel euch ein ander Evangelium predigen würde, denn das wir euch gepredigt haben, der sei verflucht. Und in der 2. Epistel zu den Corinthern am 13, 8. 10.: Wir haben keine Macht wider die Wahrheit, sondern für die Wahrheit; item: Nach der Macht, welche mir der HErr zu bessern, und nicht zu verderben gegeben hat. Also gebeut auch das geistliche Recht 2. q. 7. in cap. Sacerdotes und in cap. Oves. Und St. Augustin schreibt in der Epistel wider Petilianum: Man soll auch den Bischöfen, so ordentlich gewählt, nicht folgen, wo sie irren oder etwas wider die heilige göttliche Schrift lehren oder ordnen.',
          'Daß aber die Bischöfe sonst Gewalt und Gerichtszwang haben in etlichen Sachen, als nämlich, Ehesachen oder Zehenten, dieselben haben sie aus Kraft menschlicher Rechte. Wo aber die Ordinarien nachlässig in solchem Amt, so sind die Fürsten schuldig, sie thuns auch gern oder ungern, hierin ihren Unterthanen um Friedens willen Recht zu sprechen, zu Verhütung Unfriedens und großer Unruhe in Ländern.',
          'Weiter disputirt man, ob auch Bischöfe Macht haben, Ceremonien in der Kirche aufzurichten, desgleichen Satzungen von Speisen, Feiertagen, von unterschiedlichen Orden der Kirchendiener. Denn die den Bischöfen diese Gewalt geben, ziehen diesen Spruch Christi an, Joh. 16, 12.: Ich habe euch noch viel zu sagen, ihr aber könnets jetzt nicht tragen; wenn aber der Geist der Wahrheit kommen wird, der wird euch in alle Wahrheit führen. Dazu führen sie auch das Exempel Act. am 15, 20. 29., da sie Blut und Ersticktes verboten haben. So zieht man auch das an, daß der Sabbath in Sonntag ist verwandelt worden wider die zehen Gebote, dafür sie es achten, und wird kein Exempel so hoch getrieben und angezogen, als die Verwandlung des Sabbaths, und wollen damit erhalten, daß die Gewalt der Kirche groß sei, dieweil sie mit den zehen Geboten dispensirt und etwas daran verändert hat.',
          'Aber die Unsern lehren in dieser Frage also, daß die Bischöfe nicht Macht haben, etwas wider das Evangelium zu setzen und aufzurichten; wie denn oben angezeigt ist und die geistlichen Rechte durch die ganze neunte Distinction lehren. Nun ist dieses öffentlich wider Gottes Befehl und Wort, der Meinung Gesetze zu machen oder zu gebieten, daß man dadurch für die Sünden genug thue und Gnade erlange; denn es wird die Ehre des Verdienstes Christi verlästert, wenn wir uns mit solchen Satzungen unterwinden, Gnade zu verdienen. Es ist auch am Tage, daß um dieser Meinung willen in der Christenheit menschliche Aufsatzungen unzählig überhand genommen haben, und indeß die Lehre vom Glauben und die Gerechtigkeit des Glaubens gar ist untergedrückt gewesen; man hat täglich neue Feiertage, neue Fasten geboten, neue Ceremonien und neue Ehrerbietung der Heiligen eingesetzt, mit solchen Werken Gnade und alles Gutes bei Gott zu verdienen. Item, die menschliche Satzungen aufrichten, thun auch damit wider Gottes Gebot, daß sie Sünde setzen in der Speise, in Tagen und dergleichen Dingen, und beschweren also die Christenheit mit der Knechtschaft des Gesetzes, eben als müßte bei den Christen ein solcher Gottesdienst sein, Gottes Gnade zu verdienen, der gleich wäre dem levitischen Gottesdienst, welchen Gott sollte den Aposteln und Bischöfen befohlen haben aufzurichten, wie denn etliche davon schreiben; stehet auch wohl zu glauben, daß etliche Bischöfe mit dem Exempel des Gesetzes Mosis sind betrogen worden, daher so unzählige Satzungen gekommen sind, daß eine Todsünde sein soll, wenn man an Feiertagen eine Handarbeit thue, auch ohne Aergerniß der andern; daß eine Todsünde sei, wenn man die Siebenzeit nachläßt; daß etliche Speise das Gewissen verunreiniget; daß Fasten ein solch Werk sei, damit man Gott versöhne; daß die Sünde in einem vorbehaltenen Fall werde nicht vergeben, man ersuche denn zuvor den Vorbehalter des Falls, unangesehen, daß die geistlichen Rechte nicht von Vorbehaltung der Schuld, sondern von Vorbehaltung der Kirchenpön reden.',
          'Woher haben denn die Bischöfe Recht und Macht, solche Aufsätze der Christenheit aufzulegen, die Gewissen zu verstricken? Denn St. Peter verbeut in Geschichten der Apostel am 15, 10., das Joch auf der Jünger Hälse zu legen. Und St. Paulus sagt zu den Corinthern, daß ihnen die Gewalt zu bessern und nicht zu verderben gegeben sei. Warum mehren sie denn die Sünden mit solchen Aufsätzen? Doch hat man helle Sprüche der göttlichen Schrift, die da verbieten, solche Aufsätze aufzurichten, die Gnade Gottes damit zu verdienen, oder als sollten sie vonnöthen zur Seligkeit sein. So sagt St. Paulus zu den Colossern 2, 16. 20.: So laßt nun niemand euch Gewissen machen über Speise oder über Trank oder über bestimmte Tagen, nämlich den Feiertagen, oder neuen Monden oder Sabbathen, welches ist der Schatten von den, das zukünftig war, aber der Körper selbst ist in Christo; item: So ihr denn gestorben seid mit Christo von den weltlichen Satzungen, was lasset ihr euch denn fangen mit Satzungen, als wäret ihr lebendig? Die da sagen: Du sollst das nicht anrühren, du sollst das nicht essen noch trinken, du sollst das nicht anlegen; welches sich doch alles unter Händen verzehret, und sind Menschengebot und Lehre, und haben einen Schein der Wahrheit. Item, St. Paulus zu Tito am 1, 14. verbeut öffentlich, man soll nicht achten auf jüdische Fabeln und Menschengebote, welche die Wahrheit abwenden.',
          'So redet auch Christus selbst Matth. am 15, 14. 13. von denen, so die Leute auf Menschengebote treiben: Laßt sie fahren, sie sind der Blinden blinde Leiter, und verwirft solchen Gottesdienst und sagt: Alle Pflanzen, die mein himmlischer Vater nicht gepflanzet hat, die werden ausgereutet. So nun die Bischöfe Macht haben, die Kirchen mit unzähligen Aufsätzen zu beschweren und die Gewissen zu verstricken: warum verbeut dann die göttliche Schrift so oft, die menschlichen Aufsätze zu machen und zu hören? Warum nennet sie dieselben Teufelslehren? Sollte denn der Heilige Geist solches alles vergeblich verwarnet haben?',
          'Derhalben dieweil solche Ordnungen, als nöthig aufgerichtet, damit Gott zu versöhnen und Gnade zu verdienen, dem Evangelio entgegen sind, so ziemt sich keineswegs den Bischöfen, solche Gottesdienste zu erzwingen. Denn man muß in der Christenheit die Lehre von der christlichen Freiheit behalten, als nämlich, daß die Knechtschaft des Gesetzes nicht nöthig ist zur Rechtfertigung, wie denn St. Paulus zu den Galatern schreibt am 5, 1.: So bestehet nun in der Freiheit, damit uns Christus gefreiet hat, und laßt euch nicht wieder in das knechtische Joch verknüpfen; denn es muß je der vornehmste Artikel des Evangelions erhalten werden, daß wir die Gnade Gottes durch den Glauben an Christum ohne unser Verdienst erlangen, und nicht durch Dienst von Menschen eingesetzt verdienen.',
          'Was soll man denn halten vom Sonntag und dergleichen andern Kirchenordnungen und Ceremonien? Dazu geben die Unsern diese Antwort, daß die Bischöfe oder Pfarrherren mögen Ordnungen machen, damit es ordentlich in der Kirche zugehe, nicht damit Gottes Gnade zu erlangen, auch nicht damit für die Sünden genug zu thun, oder die Gewissen damit zu verbinden, solches für nöthigen Gottesdienst zu halten, und es dafür zu achten, daß sie Sünde thäten, wenn sie ohne Aergerniß dieselben brechen. Also hat St. Paulus zu den Corinthern (1 Cor. 11, 5. 6.) verordnet, daß die Weiber in der Versammlung ihr Haupt sollen decken; item, daß die Prediger in der Versammlung nicht zugleich alle reden, sondern ordentlich, einer nach dem andern. Solche Ordnung gebührt der christlichen Versammlung um der Liebe und Friedens willen zu halten, und den Bischöfen und Pfarrherren in diesen Fällen gehorsam zu sein, und dieselben sofern zu halten, daß einer den andern nicht ärgere; damit in der Kirche keine Unordnung oder wüstes Wesen sei; doch also, daß die Gewissen nicht beschweret werden, daß mans für solche Dinge halte, die noth sein sollten zur Seligkeit, und es dafür achte, daß sie Sünde thäten, wenn sie dieselben ohne der andern Aergerniß brechen; wie denn niemand sagt, daß das Weib Sünde thue, die mit bloßem Haupt ohne Aergerniß der Leute ausgeht.',
          'Also ist die Ordnung vom Sonntage, von der Osterfeier, von den Pfingsten und dergleichen Feier und Weise. Denn die es dafür achten, daß die Ordnung vom Sonntag für den Sabbath als nöthig aufgerichtet sei, die irren sehr; denn die heilige Schrift hat den Sabbath abgethan und lehret, daß alle Ceremonien des alten Gesetzes nach Eröffnung des Evangelions mögen nachgelassen werden; und dennoch, weil vonnöthen gewesen ist, einen gewissen Tag zu verordnen, auf daß das Volk wüßte, wann es zusammenkommen sollte, hat die christliche Kirche den Sonntag dazu verordnet und zu dieser Veränderung desto mehr Gefallens und Willens gehabt, damit die Leute ein Exempel hätten der christlichen Freiheit, daß man wüßte, daß weder die Haltung des Sabbaths noch eines andern Tages vonnöthen sei. Es sind viele unrichtige Disputationen von der Verwandlung des Gesetzes, von den Ceremonien des neuen Testaments, von der Veränderung des Sabbaths, welche alle entsprungen sind aus falscher und irriger Meinung, als müßte man in der Christenheit einen solchen Gottesdienst haben, der dem levitischen oder jüdischen Gottesdienst gemäß wäre, und als sollte Christus den Aposteln und Bischöfen befohlen haben, neue Ceremonien zu erdenken, die zur Seligkeit nöthig wären. Dieselben Irrthümer haben sich in die Christenheit eingeflochten, da man die Gerechtigkeit des Glaubens nicht lauter und rein gelehrt und geprediget hat. Etliche disputiren also vom Sonntage, daß man ihn halten müsse, wiewohl nicht aus göttlichen Rechten [dennoch schier als viel als aus göttlichen Rechten]; stellen Form und Maß, wie fern man am Feiertage arbeiten mag. Was sind aber solche Disputationes anders, denn Fallstricke des Gewissens? Denn wiewohl sie sich unterstehen, menschliche Aufsätze zu lindern und epiciren, so kann man doch keine ἐπιείκειαν oder Linderung treffen, so lange die Meinung stehet und bleibt, als sollten sie vonnöthen sein. Nun muß dieselbige Meinung bleiben, wenn man nichts weiß von der Gerechtigkeit des Glaubens und von der christlichen Freiheit. Die Apostel haben geheißen, man solle sich enthalten des Blutes und Erstickten. Wer hälts aber jetzo? Aber dennoch thun die keine Sünde, die es nicht halten; denn die Apostel haben auch selbst die Gewissen nicht wollen beschweren mit solcher Knechtschaft, sondern habens um Aergernisses willen eine Zeitlang verboten. Denn man muß Achtung haben in dieser Satzung auf das Hauptstück christlicher Lehre, das durch dieses Decret nicht aufgehoben wird.',
          'Man hält schier keine alte Canones, wie sie lauten; es fallen auch derselben Satzungen täglich viele weg, auch bei denen, die solche Aufsätze allerfleißigst halten; da kann man den Gewissen nicht rathen noch helfen, wo diese Linderung nicht gehalten wird; daß wir wissen, solche Aufsätze also zu halten, daß mans nicht dafür halte, daß sie nöthig seien, daß auch den Gewissen unschädlich sei, obgleich solche Aufsätze fallen. Es würden aber die Bischöfe leichtlich den Gehorsam erhalten, wo sie nicht darauf drüngen, diejenigen Satzungen zu halten, so doch ohne Sünde nicht mögen gehalten werden. Jetzo aber thun sie ein Ding und verbieten beide Gestalt des heiligen Sacraments; item, den Geistlichen den Ehestand; nehmen niemand auf, ehe er denn zuvor einen Eid gethan habe, er wolle diese Lehre, so doch ohne Zweifel dem heiligen Evangelio gemäß ist, nicht predigen.',
          'Unsere Kirchen begehren nicht, daß die Bischöfe mit Nachtheil ihrer Ehren und Würden wiederum Frieden und Einigkeit machen; wiewohl solches den Bischöfen in der Noth auch zu thun gebühret. Allein bitten sie darum, daß die Bischöfe etliche unbillige Beschwerungen nachlassen, die doch vor Zeiten auch in der Kirche nicht gewesen, und angenommen sind wider den Gebrauch der christlichen gemeinen Kirche; welche vielleicht im Anheben etliche Ursachen gehabt, aber sie reimen sich nicht zu unsern Zeiten. So ist es auch unleugbar, daß etliche Satzungen aus Unverstand angenommen sind; darum sollten die Bischöfe der Gütigkeit sein, dieselben Satzungen zu mildern, sintemal eine solche Aenderung nichts schadet, die Einigkeit christlicher Kirche zu erhalten; denn viele Satzungen von den Menschen aufgekommen sind mit der Zeit selbst gefallen, und nicht nöthig zu halten, wie die päbstlichen Rechte selbst zeugen. Kanns aber je nicht sein, es auch bei ihnen nicht zu erhalten, daß man solche menschlichen Satzungen mäßige und abthue, welche man ohne Sünde nicht kann halten, so müssen wir der Apostel Regel folgen, die uns gebeut, wir sollen Gott mehr gehorsam sein, denn den Menschen.',
          'St. Peter verbeut den Bischöfen die Herrschaft, als hätten sie Gewalt, die Kirchen, wozu sie wollten, zu zwingen. Jetzt geht man nicht damit um, wie man den Bischöfen ihre Gewalt nehme, sondern man bittet und begehrt, sie wollten die Gewissen nicht zu Sünden zwingen. Wenn sie aber solches nicht thun werden und diese Bitte verachten, so mögen sie gedenken, wie sie werden deshalben Gott Antwort geben müssen, dieweil sie mit solcher ihrer Härtigkeit Ursache geben zu Spaltung und Schisma, das sie doch billig sollen verhüten helfen.',
        ],
      },
      {
        id: 'beschluss',
        title: 'Beschluß.',
        sub: '',
        paragraphs: [
          'Dies sind die vornehmsten Artikel, die für streitig geachtet werden; denn wiewohl man viel mehr Mißbräuche und Unrichtigkeit hätte anziehen können, so haben wir doch, die Weitläuftigkeit und Länge zu verhüten, allein die vornehmsten vermeldet, daraus die andern leichtlich zu ermessen; denn man in Vorzeiten sehr geklagt über den Ablaß, über Wallfahrten, über Mißbrauch des Bannes. Es hatten auch die Pfarrer unendlich Gezänk mit den Mönchen von wegen des Beichthörens, des Begräbnisses, der Leichenpredigten und unzähliger anderer Stücke mehr. Solches alles haben wir im besten und um Glimpfs willen übergangen, damit man die vornehmsten Stücke in dieser Sache desto baß vermerken möchte. Dafür soll es auch nicht gehalten werden, daß in dem jemand ichtes [etwas] zu Haß, wider oder Unglimpf geredet oder angezogen sei; sondern wir haben allein die Stücke erzählet, die wir für nöthig anzuziehen und zu vermelden geachtet haben, damit man daraus desto baß zu vernehmen habe, daß bei uns nichts weder mit Lehre noch mit Ceremonien angenommen ist, das entweder der heiligen Schrift, oder gemeiner christlicher Kirche zu entgegen wäre. Denn es ist je am Tage und öffentlich, daß wir mit allem Fleiß mit Gottes Hilfe (ohne Ruhm zu reden) verhütet haben, damit je keine neue und gottlose Lehre sich in unsern Kirchen einflechte, einreiße und überhand nehme.',
          'Die obgemeldeten Artikel haben wir dem Ausschreiben nach übergeben wollen, zu einer Anzeigung unseres Bekenntnisses und der Unsern Lehre; und ob jemand befunden würde, der daran Mangel hätte, dem ist man ferner Bericht mit Grunde göttlicher heiliger Schrift zu thun erbötig.',
          'E. Kaiserl. Majestät unterthänigste',
          'Johannes, Herzog zu Sachsen, Churfürst.',
          'Georg, Markgraf zu Brandenburg.',
          'Ernst, Herzog zu Lüneburg.',
          'Philipp, Landgraf zu Hessen.',
          'Wolfgang, Fürst zu Anhalt.',
          'Die Stadt Nürnberg.',
          'Die Stadt Reutlingen.',
        ],
      },
    ],
  },
];
