/**
 * "Das Kirchenjahr nach seiner Bedeutung und Eintheilung" – the introduction of
 * Georg Christian Dieffenbach, Evangelische Haus-Agende, das ist: Vollständige
 * Ordnung des Hausgottesdienstes (Mainz 1853), pp. 1–6. Public domain (rule 12).
 * Transcribed from the Fraktur print in the original spelling (rule 16); section
 * headings are ours, the book separates its parts by a rule. The closing paragraph
 * that points to the book's own introductions to each circle is left out.
 */

export const CHURCH_YEAR_INTRO_SOURCE =
  'Georg Christian Dieffenbach, Evangelische Haus-Agende, das ist: Vollständige Ordnung des Hausgottesdienstes, Mainz 1853, Einleitung.';

export const CHURCH_YEAR_INTRO_TITLE = 'Das Kirchenjahr nach seiner Bedeutung und Eintheilung';

export const CHURCH_YEAR_INTRO: readonly { heading: string; paragraphs: readonly string[] }[] = [
  {
    heading: 'Das Wesen des Kirchenjahres',
    paragraphs: [
      'Du bist das Eigenthum deines Gottes und Heilandes, mein Christ. In der heiligen Taufe bist du ganz mit Leib, Seel und Geist übergeben dem lebendigen dreieinigen Gott, auf deß Name du ja getauft bist, und Er selbst hat in diesem Bade der Wiedergeburt dich angenommen zu Seinem Kind.',
      'Gott der Vater hat dir nicht nur das leibliche Leben gegeben, dich „sammt allen Creaturen geschaffen,“ – Er hat dir und der ganzen Menschheit, die in Sünden von Ihm abgefallen war, auch Seinen lieben Sohn gesendet, auf daß Alle die an Ihn glauben nicht verloren werden, sondern das ewige Leben haben sollten. – Gott der Sohn, dein Herr, hat dich, „armen verlorenen und verdammten Menschen erlöset, hat dich erworben und gewonnen von allen Sünden, vom Tod und von der Gewalt des Teufels, nicht mit Gold oder Silber, sondern mit Seinem heiligen theuren Blut und mit Seinem unschuldigen Leiden und Sterben, auf daß du Sein eigen seist und in Seinem Reich unter Ihm lebest und Ihm dienest in ewiger Gerechtigkeit, Unschuld und Seligkeit.“ – Gott der heilige Geist hat schon in der Taufe Seine Kraft an dir erwiesen, Er hat dich auch „durch das Evangelium berufen“ und berufet dich fort und fort, und so du folgest, erleuchtet Er dich auch mehr und mehr „mit Seinen Gaben, heiliget und erhält dich im rechten Glauben, Er verleihet dir und der ganzen Christenheit täglich und reichlich die Vergebung deiner Sünden und wird dir einst auch sammt allen Glaubigen in Christo ein ewiges Leben geben.“',
      'Das hat dein Gott für dich gethan, darum bist du Sein Eigenthum, das Er sich selber erworben hat. Sieh auf dich; du bist ein geringer, armer Mensch, – ein wenig Staub und Erde, ohnmächtig und elend; du bist beladen mit Sünden, dein ganzes Wesen ist verderbt, – und nun schaue auf zu deinem Gott und Herrn, der mit solch tiefem Erbarmen dich angesehen, der dich selbst nach Seiner freien Gnade errettet hat und dich erhoben zu Seinem Reiche und zu Seiner Herrlichkeit! Gewiß, da möchtest du niedersinken in den Staub vor deinem gnädigen Gott und im Gebete dich und dein ganzes Leben Ihm zum Opfer darbringen, Ihm, durch den allein du etwas bist, der nach Seiner Gnade dich berufen hat zu Seinem Kinde! Dein ganzes Leben möchtest du hinbringen in heiliger Feier der überschwenglichen Gnade deines Gottes und Heilandes, bis du dereinst mit allen Engeln und Seligen dort oben stehen darfst um den Thron des Lammes in ewiger, himmlischer Feier, die kein Auge je gesehen, noch kein Ohr gehört, davon auch nichts in eines Menschen Herz gekommen ist. –',
      'Die Gnade Gottes, die du erfahren hast, ist auch Andern zu Theil geworden; die ganze Gemeinde des Herrn, die heilige Kirche ist gleich dir des Herrn unsres Gottes Eigenthum.',
      'Gott der Vater hat den Sohn verheißen und gesendet zum Erlöser, nicht dir allein, sondern Allen, die an Ihn glauben. – Der Sohn hat die ganze Gemeinde geliebet und sich selbst für sie gegeben (Eph. 5, 25.); Er hat Seine Kirche mit Seinem heiligen theuren Blute erkauft und gegründet. – Der heilige Geist hat die ganze Christenheit berufen und gesammelt und waltet über der ganzen Kirche mit Seiner erleuchtenden, heiligenden und beseligenden Kraft.',
      'Darum kann es auch die Kirche nicht lassen, diese wunderbaren Gnadenerweisungen Gottes zur Erlösung der Welt fort und fort zu feiern. Es dränget sie, dem gnädigen dreieinigen Gott, deß Barmherzigkeit so reichlich über sie ausgeschüttet ist, in Gebeten und Lobgesängen Dank und Ehre zu bringen und die Thaten Seiner Liebe zu verkündigen. Was die Kirche thut, das thut sie in heiliger Ordnung, als des Herrn Jesu Christi Leib, als Seine heilige Gemeinde. Ihr ganzes Leben ist eine Feier der Gnadenerweisungen ihres Gottes nach derselben Ordnung, wie diese Thaten Gottes zur Erlösung der Welt nach und nach in’s Leben getreten sind. So schreitet die Kirche mit Gebeten voll Glauben, mit tiefinnigen Liedern und Lobgesängen, und mit Verkündigung der Thaten Gottes in heiliger Feier von Fest zu Fest. In dem Kreislauf eines Jahres ist auch der Kreislauf ihrer Feste und heiligen Gedenktage an Gottes Gnadenthaten zur Erlösung der Welt vollendet, um dann wieder von neuem anzuheben. So entsteht, eingefügt in das natürliche Jahr, ein heiliges Jahr, ein Jahr der Kirche. Wie das natürliche Jahr in stets wiederholtem Kreislauf die Thaten Gottes als des Schöpfers und Erhalters der Welt offenbaret, so offenbaret das Kirchenjahr in seinem Kreislaufe in heiliger Feier Gottes Thaten zur Erlösung der Welt.',
      'Heilige Feier der Gnadenerweisungen des dreieinigen Gottes zur Erlösung der Welt nach der Ordnung der göttlichen Thaten selbst, – das ist das Wesen des Kirchenjahres.',
    ],
  },
  {
    heading: 'Die drei Festkreise',
    paragraphs: [
      'Dreifach ist das Walten und Thun des dreieinigen Gottes im Erlösungswerke, wie vorher schon angedeutet.',
      'Gott der Vater hat von Ewigkeit her den Rathschluß gefaßt, die in Sünden gefallene Menschheit zu erlösen. Er hat diesen heiligen Rathschluß geoffenbaret von Anfang an, ihn verkündigen lassen durch Seine Propheten und Sein Volk darauf vorbereitet und erzogen. Da die Zeit erfüllet war, sandte Er Seinen lieben Sohn, wie Er zuvor verheißen hatte. Er ließ den Eingebornen, den Er liebte von Ewigkeit, in diese arme Welt eintreten als ein Menschenkind und verordnete Ihn zu einem Heiland für alle Welt.',
      'Gott der Sohn, der eins ist mit dem Vater, nimmt in heiliger Liebe das schwere Mittleramt auf sich. Er wandelt in Armuth und Niedrigkeit auf Erden, lehret das Volk und erweist sich durch Wunder und Zeichen als Prophet. Er steigt im vollen Bewußtsein Seiner göttlichen Herrlichkeit hinab in das tiefste Leiden und vollbringt als der ewige Hohepriester am Kreuzesstamm auf Golgatha das ewig gültige Versöhnungsopfer für die Sünden der Welt. Er geht endlich aus Grab und Tod siegreich hervor als ein König und Fürst des Lebens, – offenbart sich den Seinen in Seiner Herrlichkeit und steigt hinauf zum Himmel, um zur Rechten des Vaters sich niederzusetzen auf den Stuhl Seiner Majestät im Himmel.',
      'Gott der heilige Geist, vom Sohne verheißen, kommt herab auf die kleine Schaar des Herrn; da der Sohn zu Seinem Vater zurückgekehrt ist, sendet er Ihn als einen andern Tröster, damit die Seinen nicht Waisen bleiben auf Erden. Der heilige Geist hebet Sein Werk an am Pfingstfeste und waltet und wirket nun fort bis zum jüngsten Tage. Sein Amt ist es, die ganze Christenheit zu berufen und zu sammeln, zu erleuchten, zu bekehren zum Herrn, sie zu heiligen im Glauben und Leben, und endlich alle Gläubigen zur seligen Vollendung zu führen.',
      'Nach diesem dreifachen heiligen Walten des dreieinigen Gottes zur Erlösung der Welt, zerfällt das Kirchenjahr in drei Hauptabschnitte, in drei Festkreise. Diese drei Festkreise sind: 1) Der Weihnachtskreis (vom 1. Advent bis Sonnabend nach Epiphanias). 2) Der Osterkreis (vom 1. Sonntag nach Epiphanias bis Himmelfahrt). 3) Der Pfingstkreis (vom Freitag vor Exaudi bis zum letzten Tag des Kirchenjahrs).',
      'Der Weihnachtskreis umfaßt die Feier dessen, was Gott der Vater gethan hat zum Werke der Erlösung: die Verheißung und Vorbereitung auf Christum; die Sendung des Sohnes selbst und die Darstellung desselben als eines Heilandes der Welt. Dieser Festkreis ist darum der Festkreis Gottes des Vaters.',
      'Der Osterkreis umfaßt die Feier dessen, was Gott der Sohn gethan hat zur Erlösung der Welt, Sein prophetisch, hohepriesterlich und königlich Amt. Er ist darum der Festkreis Gottes des Sohnes.',
      'Der Pfingstkreis umfaßt die Feier dessen, was Gott der heilige Geist zur Erlösung wirkt. Nach einer kurzen Vorbereitungs- und Wartezeit kommt die Ausgießung des heiligen Geistes und darnach Sein Walten in der Berufung und Sammlung, in der Erleuchtung, Bekehrung, Heiligung und Vollendung der Gemeinde Gottes. Der Pfingstkreis ist darum der Festkreis Gottes des heiligen Geistes.',
      'Es versteht sich von selbst, daß hierbei nicht vergessen werden darf, daß Gott der Vater, Gott der Sohn und Gott der heilige Geist von Ewigkeit zu Ewigkeit eines Wesens sind, ein wahrer, dreieiniger Gott, und daß also auch das Walten und Thun des Vaters, des Sohnes und des heiligen Geistes nicht als ein völlig geschiednes, von einander getrenntes und trennendes gedacht werden darf. Was der Vater thut, das thut Er durch den Sohn und Geist und in heiliger Einheit mit denselben; was der Sohn thut, das thut Er in Uebereinstimmung mit dem Vater und dem heiligen Geiste; und was der heilige Geist thut und redet, das nimmt Er von dem, das des Vaters und des Sohnes ist. Wie wir aber von Gott dem Vater, Sohn und heiligen Geist als von drei unterschiedlichen Personen reden, obschon wir recht wohl wissen, daß diese drei Personen eines Wesens, ein wahrer Gott und Herr sind, – so können und müssen wir auch reden von dem unterschiedlichen Walten und Thun des Vaters, des Sohnes und des heiligen Geistes zur Erlösung der Welt, ohne daß hiermit die Einheit des Wesens und Willens aufgehoben wäre. – Gleichwie die drei Festkreise eng mit einander verbunden sind und so das eine heilige Jahr bilden, – so ist das Walten und Thun des Vaters, des Sohnes und des heiligen Geistes zur Erlösung der Welt, welches in den drei Festkreisen in heiliger Ordnung sich darstellt, eng verbunden, und ist in seinem tiefsten Grunde ein gnadenreich Werk der Erlösung, dessen Feier das ganze heilige Jahr gewidmet ist.',
    ],
  },
  {
    heading: 'Kirchenjahr und Naturjahr',
    paragraphs: [
      'Der Weihnachtskreis feiert die stille Vorbereitung des Erlösungswerkes; der Osterkreis die herrliche Ausführung desselben, das Werk selbst; der Pfingstkreis die Aneignung und Reife der erworbnen Gnadengüter in der Gemeinde bis zur Vollendung.',
      'In eigenthümlicher Weise tritt hier eine schöne Harmonie zwischen dem Natur-Jahre, wie es bei uns verläuft, und dem Kirchen-Jahre uns entgegen: –',
      'Die Zeit des Weihnachtskreises ist auch für die Natur die Zeit der stillen, geheimnißvollen Vorbereitung auf die kommenden Tage des neuen Lebens.',
      'Die Zeit des Osterkreises ist für die Natur die Zeit, da zuerst im Verborgenen das neue Leben erwacht; darnach hebet ein Schaffen und Ringen an, ein neues Wirken und Weben; die Natur ist in voller Thätigkeit, die winterlichen Hüllen springen auf, das im Verborgenen vorbereitete neue Leben tritt in die Welt ein; immer reicher, voller, herrlicher entwickelt es sich, bis es um die Zeit der Himmelfahrt Christi, am Ende des Osterkreises (im Mai) in reichster Fülle vor uns sich entfaltet hat und die ganze Natur aufjubelt zum Himmel.',
      'Die Zeit des Pfingstkreises ist die Zeit, da Alles reift und sich vollendet. Das Keimen und Wachsen, das Drängen und Schaffen ist vorüber. Stilles Walten und Weben herrscht in der Natur; die Früchte reifen langsam dem Herbste entgegen. Der Herbst bringt keine Unterbrechung; er kündigt sich nicht durch ein ganz neues Werk an, sondern aus dem Sommer reift Alles allmählich hinüber in den Herbst bis zum Tag der Aernte, da die Früchte des Jahres gesammelt werden in die Scheunen und das Unkraut vom guten Gewächs, die Spreu vom Weizen gesondert wird. Dann tritt wieder ein die Zeit der Ruhe, der stillen, geheimnißvollen Vorbereitung und so in schön geordnetem Kreislaufe schreitet in dreifacher Entwicklung das Naturjahr dahin, bis einst der Herr alle Zeit aufhebt und in die Ewigkeit versenket. – Ahnungen des höheren Lebens liegen also im Weben und Walten des Naturlebens. –',
    ],
  },
];

/** The doxology with which the introduction ends. */
export const CHURCH_YEAR_INTRO_GLORIA =
  'Ehre sei dem Vater und dem Sohne und dem heiligen Geiste, wie es war von Anfang und jetzt und immerdar sein wird in die ewigen Ewigkeiten. Halleluja!';
