/**
 * The Smalcald Articles (1537), word for word after the Book of Concord,
 * St. Louis 1881 (after the text of 1580), pp. 219–240. Read from the scan
 * at archive.org by two OCR models, checked against the Triglotta (1921)
 * and, where they disagreed, against the page image.
 */
import type { BookPart } from './augsburgConfession';
import { CONCORDIA } from './creeds';

export const SMALCALD_SOURCE = `${CONCORDIA}, S. 219–240.`;

/** The title as the book prints it above the preface. */
export const SMALCALD_TITLE =
  'Artikel christlicher Lehre, so da hätten sollen aufs Concilium zu Mantua, oder wo es sonst worden wäre, überantwortet werden von unsers Theils wegen, und was wir annehmen oder nachgeben könnten oder nicht etc. Durch D. Martin Luther geschrieben Anno 1537.';


export const SMALCALD_ARTICLES: readonly BookPart[] = [
  {
    sections: [
      {
        id: 'vorrede',
        title: 'Vorrede Doct. Mart. Luthers.',
        sub: '',
        paragraphs: [
          'Da der Pabst Paulus, des Namens der dritte, ein Concilium ausschrieb im vergangenen Jahr, auf die Pfingsten zu Mantua zu halten, und hernach von Mantua wegrückte, daß man noch nicht weiß, wohin ers legen will oder kann, und wir uns auf unsern Theil versehen sollten, daß wir entweder auch zum Concilio berufen oder unberufen verdammt würden: ward mir befohlen, Artikel unserer Lehre zu stellen und zusammen bringen, obs zur Handlung käme, was und wiefern wir wollten oder könnten den Papisten weichen, und auf welchen wir gedächten endlich zu beharren und zu bleiben.',
          'Demnach habe ich diese Artikel zusammengebracht und unserm Theil überantwortet. Die sind auch von den Unsern angenommen und einträchtiglich bekennet, und beschlossen, daß man sie solle (wo der Pabst mit den Seinen einmal so kühn wollte werden, ohne Lügen und Trügen, mit Ernst und wahrhaftig ein recht frei, christlich Concilium zu halten, wie er wohl schuldig wäre) öffentlich überantworten und unsers Glaubens Bekenntniß vorbringen.',
          'Aber weil sich der römische Hof so greulich vor einem freien christlichen Concilio fürchtet und das Licht so schändlich fleucht, daß er auch denen, die seines Theils sind, die Hoffnung genommen hat, als werde er nimmermehr ein frei christlich Concilium leiden, viel weniger selbst halten; daran sie sich denn, wie billig, fast ärgern und nicht geringe Beschwerungen darüber haben, als die daran merken, daß der Pabst lieber wollte die ganze Christenheit verloren und alle Seelen verdammt sehen, ehe er sich oder die Seinen wollte ein wenig reformieren und seiner Tyrannei ein Maß setzen lassen: so hab ich gleichwohl diese Artikel indeß wollen durch öffentlichen Druck an den Tag geben, ob ich ja ehe sterben sollte, denn ein Concilium würde (wie ich mich ganz versehe und verhoffe), weil die lichtflüchtigen und tagscheuenden Schelme so jämmerlich Mühe haben, das Concilium zu verziehen und zu verhindern; damit die, so nach mir leben und bleiben werden, mein Zeugniß und Bekenntniß haben vorzuwenden über das Bekenntniß, das ich zuvor habe lassen ausgehen, darauf ich auch noch bisher geblieben bin und bleiben will mit Gottes Gnade.',
          'Denn was soll ich sagen? Wie soll ich klagen? Ich bin noch im Leben, schreibe, predige und lese täglich, noch finden sich solche giftige Leute, nicht allein unter den Widersachern, sondern auch falsche Brüder, die unsers Theils sein wollen, die sich unterstehen, meine Schrift und Lehre stracks wider mich zu führen, lassen mich zusehen und zuhören, ob sie wohl wissen, daß ich anders lehre, und wollen ihr Gift mit meiner Arbeit schmücken und die armen Leute unter meinem Namen verführen: was will doch immermehr nach meinem Tode werden?',
          'Ja, ich sollte billig alles verantworten, weil ich noch lebe. Ja wiederum, wie kann ich allein alle Mäuler des Teufels stopfen? sonderlich denen (wie sie alle vergiftet sind), die nicht hören noch merken wollen, was wir schreiben, sondern allein an dem sich üben mit allem Fleiß, wie sie unsere Worte in allen Buchstaben aufs schändlichste verkehren und verderben mögen. Solchen lasse ich den Teufel antworten oder zuletzt Gottes Zorn, wie sie verdienen. Ich denke oft an den guten Gerson, der zweifelte, ob man etwas Gutes sollte öffentlich schreiben; thut mans nicht, so werden viele Seelen versäumt, die man könnte erretten; thut mans aber, so ist der Teufel da mit unzähligen giftigen, bösen Mäulern, die alles vergiften und verkehren, daß doch die Frucht verhindert wird. Doch was sie daran gewinnen, sieht man am Tage; denn sintemal sie so schändlich wider uns gelogen und die Leute mit Lügen haben wollen behalten, hat Gott sein Werk immer fort getrieben, ihren Haufen immer kleiner und unsern größer gemacht und sie mit ihren Lügen zu Schanden lassen werden und noch immer fort.',
          'Ich muß eine Historia sagen. Es ist hie zu Wittenberg gewesen aus Frankreich ein Doctor gesandt, der vor uns öffentlich sagte, daß sein König gewiß und übergewiß wäre, daß bei uns keine Kirche, keine Oberkeit, kein Ehestand sei, sondern ginge alles unter einander wie das Vieh und thäte jedermann, was er wollte. Nun rathe, wie werden uns an jenem Tage vor dem Richtstuhl Christi ansehen die, so solche grobe Lügen dem Könige und andern Landen durch ihre Schrift eingebildet haben für eitel Wahrheit? Christus, unser aller HErr und Richter, weiß ja wohl, daß sie lügen und gelogen haben, deß Urtheil werden sie wiederum müssen hören; das weiß ich fürwahr. Gott bekehre, die zu bekehren sind, zur Buße; den andern wirds heißen: wehe und Ach ewiglich.',
          'Und daß ich wieder komme zur Sache, möchte ich fürwahr wohl gern ein recht christlich Concilium sehen, damit doch viel Sachen und Leuten geholfen würde; nicht daß wirs bedürfen, denn unsere Kirchen sind nun durch Gottes Gnade mit dem reinen Wort und rechtem Brauch der Sacramente, mit Erkenntniß allerlei Ständen und rechten Werken also erleuchtet und beschickt, daß wir unserthalben nach keinem Concilio fragen und in solchen Stücken vom Concilio nichts Besseres zu hoffen noch zu gewarten wissen. Sondern da sehen wir in den Bisthümern allenthalben viel Pfarren ledig und wüst, daß einem das Herz möchte brechen. Und fragen doch weder Bischöfe noch Thumherren darnach, wie die armen Leute leben oder sterben, für welche doch Christus ist gestorben, und sollen denselben nicht hören mit ihnen reden als den rechten Hirten mit seinen Schafen; daß mir grauet und bange ist, er möchte einmal einst ein Engelconcilium lassen gehen über Deutschland, das uns alle in Grund verderbte, wie Sodom und Gomorra, weil wir sein so freventlich mit dem Concilio spotten.',
          'Ueber solche nöthige Kirchensachen wären auch in weltlichem Stande unzählige große Stücke zu bessern. Da ist Uneinigkeit der Fürsten und Stände, Wucher und Geiz sind wie eine Sindfluth eingerissen und eitel Recht worden, Muthwille, Unzucht, Uebermuth mit Kleidern, Fressen, Spielen, Prangen, mit allerlei Untugend und Bosheit, Ungehorsam der Unterthanen, Gesinde und Arbeiter, aller Handwerke, auch der Bauern Uebersetzung (und wer kanns alles erzählen?) haben also überhand genommen, daß mans mit zehn Conciliis und zwanzig Reichstagen nicht wieder wird zurecht bringen. Wenn man solche Hauptstücke des geistlichen und weltlichen Standes, die wider Gott sind, im Concilio würde handeln, so würde man wohl zu thun kriegen alle Hände voll, daß man dieweil wohl würde vergessen des Kinderspiels und Narrenwerks von langen Röcken, großen Platten, breiten Gürteln, Bischofs- und Cardinalshüten oder Stäben und dergleichen Gaukelei. Wenn wir zuvor hätten Gottes Gebot und Befehl ausgerichtet im geistlichen und weltlichen Stande, so wollten wir Zeit genug finden, die Speisen, Kleider, Platten und Casel zu reformiren. Wenn wir aber solche Kamele verschlingen und dafür Mücken seigen, die Balken lassen stehen und die Splitter richten wollen, so möchten wir wohl auch mit dem Concilio zufrieden sein.',
          'Darum hab ich wenig Artikel gestellet; denn wir ohne das von Gott so viel Befehl haben, in der Kirche, in der Oberkeit, im Hause zu thun, daß wir sie nimmermehr ausrichten können. Was solls denn? oder wozu hilfts, daß man drüber viel Decrete und Satzungen im Concilio macht, sonderlich, so man diese Hauptstücke, von Gott geboten, nicht achtet noch hält? Gerade als müßte er unser Gaukelspiel feiern, dafür, daß wir seine ernsten Gebote mit Füßen treten. Aber unsere Sünden drücken uns und lassen Gott nicht gnädig über uns sein; denn wir büßen auch nicht, wollen dazu noch allen Greuel vertheidigen.',
          'Ach, lieber HErr JEsu Christe, halte du selber Concilium und erlöse die Deinen durch deine herrliche Zukunft. Es ist mit dem Pabst und den Seinen verloren; sie wollen dein nicht. So hilf du uns Armen und Elenden, die wir zu dir seufzen und dich suchen mit Ernst, nach der Gnade, die du uns gegeben hast, durch deinen Heiligen Geist, der mit dir und dem Vater lebet und regieret, ewiglich gelobet. Amen.',
        ],
      },
      {
        id: 'teil1',
        title: 'Das erste Theil.',
        sub: 'Von den hohen Artikeln der göttlichen Majestät.',
        paragraphs: [
          'Das erste Theil ist von den hohen Artikeln der göttlichen Majestät, als:',
          'I. Daß Vater, Sohn und Heiliger Geist, in Einem göttlichen Wesen und Natur, drei unterschiedliche Personen, ein einiger Gott ist, der Himmel und Erde geschaffen hat.',
          'II. Daß der Vater von niemand, der Sohn vom Vater geboren, der Heilige Geist vom Vater und Sohn ausgehend.',
          'III. Daß nicht der Vater, noch Heiliger Geist, sondern der Sohn sei Mensch worden.',
          'IV. Daß der Sohn sei also Mensch worden, daß er vom Heiligen Geist ohne männlich Zuthun empfangen, und von der reinen, heiligen Jungfrauen Maria geboren sei. Darnach gelitten, gestorben, begraben, zur Hölle gefahren, auferstanden von den Todten, aufgefahren gen Himmel, sitzend zur Rechten Gottes, künftig zu richten die Lebendigen und die Todten etc. Wie der Apostel, item St. Athanasii Symbolum und der gemeine Kinderkatechismus lehret.',
          'Diese Artikel sind in keinem Zank noch Streit, weil wir zu beiden Theilen dieselbigen bekennen. Darum nicht vonnöthen, jetzt davon weiter zu handeln.',
        ],
      },
      {
        id: 'teil2',
        title: 'Das andere Theil.',
        sub: 'Der I. und Hauptartikel.',
        paragraphs: [
          'Das andere Theil ist von den Artikeln, so das Amt und Werk JEsu Christi oder unsere Erlösung betreffen.',
          'Hie ist der I. und Hauptartikel:',
          'Daß JEsus Christus, unser Gott und HErr, sei um unserer Sünden willen gestorben und um unserer Gerechtigkeit willen auferstanden, Röm. 4.',
          'Und er allein das Lamm Gottes ist, das der Welt Sünde trägt, Joh. 1. Und Gott unser aller Sünde auf ihn gelegt hat, Es. 53.',
          'Item: Sie sind allzumal Sünder und werden ohne Verdienst gerecht aus seiner Gnade durch die Erlösung JEsu Christi in seinem Blut etc. Röm. 3.',
          'Dieweil nun solches muß geglaubt werden und sonst mit keinem Werk, Gesetz noch Verdienst mag erlangt oder gefaßt werden, so ist es klar und gewiß, daß allein solcher Glaube uns gerecht mache; wie Röm. 3. St. Paulus spricht: Wir halten, daß der Mensch gerecht werde ohne Werke des Gesetzes durch den Glauben; item: auf daß er allein gerecht sei und gerecht mache den, der da ist des Glaubens an JEsu.',
          'Von diesem Artikel kann man nichts weichen oder nachgeben, es falle Himmel und Erde oder was nicht bleiben will. Denn es ist kein anderer Name den Menschen gegeben, dadurch wir können selig werden, spricht Petrus Act. 4.; und durch seine Wunden sind wir geheilet, Es. 53. Und auf diesem Artikel stehet alles, das wir wider den Pabst, Teufel und Welt lehren und leben. Darum müssen wir deß gar gewiß sein, und nicht zweifeln, sonst ist es alles verloren und behält Pabst und Teufel und alles wider uns den Sieg und Recht.',
        ],
      },
      {
        id: 'art2',
        title: 'Der II. Artikel.',
        sub: 'Von der Messe.',
        paragraphs: [
          'Daß die Messe im Pabstthum muß der größeste und schrecklichste Greuel sein, als die stracks und gewaltiglich wider diesen Hauptartikel strebet, und doch über und vor allen andern päbstlichen Abgöttereien die höchste und schönste gewesen ist; denn es ist gehalten, daß solch Opfer oder Werk der Messe (auch durch einen bösen Buben gethan) helfe dem Menschen von Sünden, beide hie im Leben und dort im Fegfeuer, welches doch allein soll und muß thun das Lamm Gottes, wie droben gesagt. Von diesem Artikel ist auch nicht zu weichen oder nachzulassen; denn der erste Artikel leidets nicht.',
          'Und wo etwa vernünftige Papisten wären, möchte man dermaßen und freundlicher Weise mit ihnen reden: Erstlich, warum sie doch so hart an der Messe hielten? Ists doch ein lauter Menschenfündlein, von Gott nicht geboten. Und alle Menschenfündlein mögen wir fallen lassen, wie Christus spricht Matth. 15.: Sie dienen mir vergeblich mit Menschengeboten.',
          'Zum andern, ist ein unnöthig Ding, das man ohne Sünde und Fahr wohl lassen kann.',
          'Zum dritten, kann man das Sacrament viel besserer und seliger Weise (ja allein seliger Weise) nach Christus Einsetzung kriegen: was ists denn, daß man um einer erdichteten, unnöthigen Sache willen, da mans sonst wohl und seliger haben kann, die Welt in Jammer und Noth wollte zwingen?',
          'Man lasse den Leuten öffentlich predigen, wie die Messe als ein Menschentand möge ohne Sünde nachbleiben, und niemand verdammt werde, wer sie nicht achte, sondern möge wohl ohne Messe, durch bessere Weise selig werden: was gilt, ob die Messe alsdann nicht von ihr selbst fallen wird, nicht allein bei dem tollen Pöbel, sondern auch bei allen frommen, christlichen, vernünftigen, gottfürchtigen Herzen? Vielmehr wo sie hören würden, daß es ein fährlich Ding, ohne Gottes Wort und Willen erdichtet und erfunden ist.',
          'Zum vierten, weil solche unzählige, unaussprechliche Mißbräuche in aller Welt mit Kaufen und Verkaufen der Messen entstanden, sollte man sie billig lassen fahren, auch allein, solchen Mißbräuchen zu wehren, wenn sie gleich an ihr selbst etwas Nützliches und Gutes hätte: wie viel mehr soll man sie fahren lassen, solche Mißbräuche ewiglich zu verhüten, weil sie doch gar unnöthig, unnütz und fährlich ist und man alles nöthiger, nützlicher und gewisser ohne die Messe haben kann.',
          'Zum fünften, nun aber die Messe nichts anderes ist noch sein kann (wie der Canon und alle Bücher sagen), denn ein Werk der Menschen (auch böser Buben), damit einer sich selbst und andere mit sich gegen Gott versöhnen, Vergebung der Sünden und Gnade erwerben und verdienen will (denn also wird sie gehalten, wenn sie aufs allerbeste wird gehalten; was sollte sie sonst?), so soll und muß man sie verdammen und verwerfen. Denn das ist stracks wider den Hauptartikel, der da sagt, daß nicht ein böser oder frommer Meßknecht mit seinem Werk, sondern das Lamm Gottes und Sohn Gottes unsere Sünde trägt.',
          'Und ob einer zum guten Schein wollte vorgeben, er wollte zur Andacht sich selbst berichten oder communiciren, das ist nicht Ernst. Denn wo er mit Ernst will communiciren, so hat ers gewiß und aufs beste im Sacrament, nach der Einsetzung Christi gereicht. Aber sich selbst communiciren ist ein Menschendünkel, ungewiß und unnöthig, dazu verboten. Und er weiß auch nicht, was er macht, weil er ohne Gottes Wort falschem Menschendünkel und Fündlein folgt. So ists auch nicht Recht (wenn alles sonst schlecht wäre), daß einer das gemeine Sacrament der Kirche nach seiner eigener Andacht will brauchen und damit seines Gefallens ohne Gottes Wort außer der Kirche Gemeinschaft spielen.',
          'Dieser Artikel von der Messe wirds ganz und gar sein im Concilio. Denn wo es möglich wäre, daß sie uns alle anderen Artikel nachgäben, so können sie doch diesen Artikel nicht nachgeben. Wie der Campegius zu Augsburg gesagt, er wollte sich ehe auf Stücken zerreißen lassen, ehe er wollte die Messe fahren lassen. So werde ich mich auch, mit Gottes Hilfe, ehe lassen zu Asche machen, ehe ich einen Meßknecht mit seinem Werke, er sei gut oder böse, lasse meinem HErrn und Heiland JEsu Christo gleich oder höher sein. Also sind und bleiben wir ewiglich geschieden und wider einander. Sie fühlens wohl, wo die Messe fällt, so liegt das Pabstthum; ehe sie das lassen geschehen, so tödten sie uns alle, wo sie es vermögen.',
          'Ueber das alles hat dieser Drachenschwanz, die Messe, viel Ungeziefer und Geschmeiß mancherlei Abgötterei gezeugt.',
          'Erstlich das Fegfeuer; da hat man mit Seelmessen, Vigilien, dem Siebenten, dem Dreißigsten und jährlichen Begängnissen, zuletzt mit der Gemein-Woche und Aller Seelen Tag und Seelbad ins Fegfeuer gehandelt, daß die Messe schier allein für die Todten gebraucht ist, so doch Christus das Sacrament allein für die Lebendigen gestiftet hat. Darum ist das Fegfeuer mit allem seinem Gepränge, Gottesdienst und Gewerbe für ein lauter Teufelsgespenst zu achten. Denn es ist auch wider den Hauptartikel, daß allein Christus, und nicht Menschenwerk, den Seelen helfen soll. Ohne daß sonst auch uns nichts von den Todten befohlen noch geboten ist. Derhalben mag man es wohl lassen, wenn es schon kein Irrthum noch Abgötterei wäre.',
          'Die Papisten führen hie Augustinum und etliche Väter, die vom Fegfeuer sollen geschrieben haben, und meinen, wir sehen nicht, wozu und wohin sie solche Sprüche führen, St. Augustinus schreibt nicht, daß ein Fegfeuer sei, hat auch keine Schrift, die ihn dazu zwinge, sondern läßt es im Zweifel hangen, ob eins sei, und sagt, seine Mutter habe begehrt, daß man ihrer sollte gedenken bei dem Altar oder Sacrament, Nun, solches alles ist ja nichts, denn Menschenandacht gewesen einzeler Personen, die keine Artikel des Glaubens (welches allein Gott zugehört) stiften.',
          'Aber unsere Papisten führen solcMenchenwort dahin, daß man solle glauben ihrem schändlichen, lästerlichen, verfluchten Jahrmarkt von Seelmessen ins Fegfeuer zu opfern etc. Solches werden sie noch lange nicht aus St. Augustino beweisen. Wenn sie nun den fegfeuerischen Messenjahrmarkt abgethan haben, davon St. Augustinus nie geträumet hat, alsdann wollen wir mit ihnen reden, ob St. Augustinus Wort ohne Schrift möge zu dulden sein und der Todten gedacht werden bei dem Sacrament. Es gilt nicht, daß man aus der heiligen Väter Werk oder Wort Artikel des Glaubens machet, sonst müßte auch ein Artikel des Glaubens werden, was sie für Speise, Kleider, Häuser etc. gehabt hätten, wie man mit dem Heiligthum gethan hat. Es heißt: Gottes Wort soll Artikel des Glaubens stellen und sonst niemand, auch kein Engel.',
          'Zum andern, ist das daraus gefolgt, daß die bösen Geister haben viel Büberei angerichtet, daß sie als Menschenseelen erschienen sind, Messen, Vigilien, Wallfahrten und andere Almosen geheischt, mit unsäglichen Lügen und Schalkheiten; welches wir alle haben für Artikel des Glaubens halten und darnach leben müssen, und der Pabst solches bestätigt, wie auch die Messe und alle andere Greuel. Hie ist auch kein Weichen oder Nachlassen.',
          'Zum dritten die Wallfahrten; da hat man auch gesucht Messen, Vergebung der Sünden und Gottes Gnade; denn die Messe hats alles regiert. Nun ist das ja gewiß, daß solche Wallfahrten ohne Gottes Wort, uns nicht geboten, auch nicht vonnöthen, weil wirs wohl besser haben mögen und sie ohne alle Sünde und Fahr lassen mögen. Warum läßt man denn daheim eigene Pfarren, Gottes Wort, Weib und Kind etc., die nöthig und geboten sind, und läuft den unnöthigen, ungewissen, schädlichen Teufelsirrwischen nach? Ohne daß der Teufel den Pabst geritten hat, solches zu preisen und bestätigen, damit die Leute ja häufig von Christo auf ihre eigenen Werke fielen und abgöttisch würden, welches das Aergste dran ist, über das, daß es unnöthig, ungeboten, ungerathen und ungewiß, dazu schädlich Ding ist. Darum ist hie auch kein Weichen oder Nachgeben etc. Und man lasse solches predigen, daß es unnöthig, dazu fährlich sei, darnach sehen, wo Wallfahrten bleiben.',
          'Zum vierten die Brüderschaften, da sich die Klöster, Stifter, auch Vicaristen haben verschrieben und mitgetheilt (rechtes und redliches Kaufs) alle Messen, gute Werke etc., beide für Lebendige und Todte; welches nicht allein eitel Menschentand, ohne Gottes Wort, ganz unnöthig und ungeboten, sondern auch wider den ersten Artikel der Erlösung ist, darum keineswegs zu leiden.',
          'Zum fünften das Heiligthum, darin so manche öffentliche Lügen und Narrenwerk erfunden, von Hunds- und Roßknochen, das auch um solcher Büberei willen, deß der Teufel gelacht hat, längst sollte verdammt worden sein, wenn gleich etwas Gutes dran wäre; dazu auch ohne Gottes Wort, weder geboten noch gerathen, ganz unnöthig und unnütz Ding ist. Aber das Aergste, daß es auch hat müssen Ablaß und Vergebung der Sünden wirken, als ein gut Werk und Gottesdienst, wie die Messe etc. Zum sechsten, hie gehöret her der liebe Ablaß, so beide den Lebendigen und Todten ist gegeben (doch um Geld), und der leidige Judas oder Pabst das Verdienst Christi, sammt den übrigen Verdiensten aller Heiligen und der ganzen Kirche darin verkauft etc. Welches alles nicht zu leiden ist und auch nicht allein ohne Gottes Wort, ohne Noth, ungeboten, sondern zuwider ist dem ersten Artikel. Denn Christus Verdienst nicht durch unser Werk oder Pfennig, sondern durch den Glauben aus Gnaden erlangt wird, ohne alles Geld und Verdienst, nicht durchs Pabsts Gewalt, sondern durch die Predigt oder Gottes Wort vorgetragen.',
        ],
      },
      {
        id: 'anrufung',
        title: 'Von Anrufung der Heiligen.',
        sub: '',
        paragraphs: [
          'Anrufung der Heiligen ist auch der endechristischen Mißbräuche einer und streitet wider den ersten Hauptartikel und tilget die Erkenntniß Christi; ist auch nicht geboten noch gerathen, hat auch kein Exempel der Schrift, und habens alles tausendmal besser an Christo, wenn jenes gleich köstlich Gut wäre, als doch nicht ist.',
          'Und wiewohl die Engel im Himmel für uns bitten (wie Christus selber auch thut), also auch die Heiligen auf Erden, oder vielleicht auch im Himmel, so folgt daraus nicht, daß wir die Engel und Heiligen anrufen, anbeten, ihnen fasten, feiern, Messe halten, opfern, Kirchen, Altar, Gottesdienst stiften, und andere Weise mehr dienen, und sie für Nothhelfer halten und allerlei Hilfe unter sie theilen und jeglichem eine sonderliche zueignen sollten, wie die Papisten lehren und thun; denn das ist Abgötterei, und solche Ehre gehört Gott allein zu. Denn du kannst als ein Christ und Heiliger auf Erden für mich bitten, nicht in einerlei, sondern in allen Nöthen. Aber darum soll ich dich nicht anbeten, anrufen, feiern, fasten, opfern, Messe halten dir zu Ehren und auf dich meinen Glauben zur Seligkeit setzen. Ich kann dich sonst wohl ehren, lieben und dir danken in Christo. Wenn nun solche abgöttische Ehre von den Engeln und todten Heiligen weggethan wird, so wird die andere Ehre ohne Schaden sein, ja bald vergessen werden. Denn wo der Nutz und Hilfe, beide leiblich und geistlich, nicht mehr zu hoffen ist, werden sie die Heiligen wohl mit Frieden lassen, beide im Grabe und im Himmel; denn umsonst oder aus Liebe wird ihrer niemand viel gedenken, achten noch ehren.',
          'Und in Summa, was die Messe ist, was daraus gekommen ist, was daran hanget, das können wir nicht leiden und müssens verdammen, damit wir das heilige Sacrament rein und gewiß, nach der Einsetzung Christi, durch den Glauben gebraucht und empfangen, behalten mögen.',
        ],
      },
      {
        id: 'art3',
        title: 'Der III. Artikel.',
        sub: 'Von Stiften und Klöstern.',
        paragraphs: [
          'Daß die Stifter und Klöster, vor Zeiten guter Meinung gestiftet, zu erziehen gelehrte Leute und züchtige Weibsbilder, sollten wiederum in solchem Brauch geordnet werden, damit man Pfarrherren, Prediger und andere Kirchendiener haben möge; auch sonst nöthige Personen zu weltlichem Regiment in Städten und Ländern, auch wohlgezogene Jungfrauen zu Hausmüttern und Haushälterinnen etc.',
          'Wo sie dazu nicht dienen wollen, ists besser, man lasse sie wüste liegen oder reiße sie ein, denn daß sie sollten mit ihrem lästerlichen Gottesdienst durch Menschen erdichtet, als etwas Besseres, denn der gemeine Christenstand und von Gott gestiftet Aemter und Orden gehalten werden. Denn das ist alles auch wider den ersten Hauptartikel von der Erlösung JEsu Christi. Zudem, daß sie auch (wie alle andere Menschenfündlein) nicht geboten, nicht vonnöthen, nicht nütze, dazu fährliche und vergebliche Mühe machen, wie die Propheten solche Gottesdienste Aven, das ist, Mühe heißen.',
        ],
      },
      {
        id: 'art4',
        title: 'Der IV. Artikel.',
        sub: 'Vom Pabstthum.',
        paragraphs: [
          'Daß der Pabst nicht sei jure divino oder aus Gottes Wort das Haupt der ganzen Christenheit (denn das gehöret einem allein zu, der heißt JEsus Christus), sondern allein Bischof oder Pfarrherr der Kirche zu Rom und derjenigen, so sich williglich oder durch menschliche Kreatur (das ist, weltliche Oberkeit) zu ihm begeben haben, nicht unter ihm als einem Herrn, sondern neben ihm als Brüder und Gesellen, Christen zu sein, wie solches auch die alten Concilia und die Zeit St. Cypriani weisen.',
          'Jetzt aber darf kein Bischof den Pabst Bruder heißen, wie zu der Zeit, sondern muß ihn seinen allergnädigsten Herrn heißen, wenns auch ein König oder Kaiser wäre. Das wollen, sollen und können wir nicht auf unser Gewissen nehmen; wer es aber thun will, der thue es ohne uns.',
          'Hieraus folgt, daß alle dasjenige, so der Pabst aus solcher falscher, freveler, lästerlicher, angemaßter Gewalt gethan und vorgenommen hat, eitel teuflisch Geschicht und Geschäft gewesen und noch sei (ohne was das leibliche Regiment belangt, darin Gott auch wohl durch einen Tyrannen und Buben läßt einem Volk viel Guts geschehen), zu Verderbung der ganzen heiligen christlichen Kirche (so viel an ihm gelegen) und zu verstören den ersten Hauptartikel von der Erlösung JEsu Christi.',
          'Denn da stehen alle seine Bullen und Bücher, darin er brüllet wie ein Löwe (als der Engel Apok. 12. bildet), daß kein Christ könne selig werden, er sei denn ihm gehorsam und unterthan in allen Dingen, was er will, was er sagt, was er thut. Welches alles nichts anders ist, denn also viel gesagt: wenn du gleich an Christum glaubest und alles an ihm hast, was zur Seligkeit noth ist, so ists doch nichts und alles umsonst, wo du mich nicht für deinen Gott hältst, mir unterthan und gehorsam bist. So es doch offenbarlich ist, daß die heilige Kirche ohne Pabst gewesen zum wenigsten über fünfhundert Jahr, und bis auf diesen Tag die griechische und viel anderer Sprachen Kirchen noch nie unter dem Pabst gewesen und noch nicht sind. So ists, wie oft gesagt, ein Menschengedicht, das nicht geboten, ohne Noth und vergeblich; denn die heilige, christliche Kirche ohne solch Haupt wohl bleiben kann und wohl besser geblieben wäre, wo solch Haupt durch den Teufel nicht aufgeworfen wäre. Und ist auch das Pabstthum kein nütze in der Kirche, denn es übt kein christlich Amt, und muß also die Kirche bleiben und bestehen ohne den Pabst.',
          'Und ich setze, daß der Pabst wollte sich deß begeben, daß er nicht jure divino oder aus Gottes Gebot der Oberste wäre, sondern, damit die Einigkeit der Christen wider die Rotten und Ketzerei desto baß erhalten würde, müßte man ein Haupt haben, daran sich die andern alle hielten; solches Haupt würde nun durch Menschen erwählt, und stünde in menschlicher Wahl und Gewalt, dasselbe Haupt zu ändern, zu entsetzen, wie zu Constanz das Concilium fast die Weise hielt mit den Päbsten, setzten der dreie ab und wählten den vierten: ich setze nun (sage ich), daß sich der Pabst und der Stuhl zu Rom solches begeben und annehmen wollte, welches doch unmöglich ist, denn er müßte sein ganz Regiment und Stand lassen umkehren und zerstören mit allen seinen Rechten und Büchern; Summa, er kanns nicht thun: dennoch wäre damit der Christenheit nichts geholfen und würden viel mehr Rotten werden, denn zuvor. Denn weil man solchem Haupt nicht müßte unterthan sein aus Gottes Befehl, sondern aus menschlichem gutem Willen, würde es gar leichtlich und bald verachtet, zuletzt kein Glied behalten; müßte auch nicht immerdar zu Rom oder anderm Ort sein, sondern wo und in welcher Kirche Gott einen solchen Mann hätte gegeben, der tüchtig dazu wäre. O das wollte ein weitläuftig, wüste Wesen werden.',
          'Darum kann die Kirche nimmermehr baß regieret und erhalten werden, denn daß wir alle unter Einem Haupt Christo leben, und die Bischöfe alle, gleich nach dem Amt (ob sie wohl ungleich nach den Gaben), fleißig zusammenhalten in einträchtiger Lehre, Glauben, Sacramenten, Gebeten und Werken der Liebe etc.; wie St. Hieronymus schreibt, daß die Priester zu Alexandria sämmtlich und ingemein die Kirche regierten, und die Apostel auch gethan und hernach alle Bischöfe in der ganzen Christenheit, bis der Pabst seinen Kopf über alle erhub.',
          'Dies Stück zeigt gewaltiglich, daß er der rechte Endechrist oder Widerchrist sei, der sich über und wider Christum gesetzt und erhöhet hat, weil er will die Christen nicht lassen selig sein ohne seine Gewalt, welche doch nichts ist, von Gott nicht geordnet noch geboten. Das heißt eigentlich über Gott und wider Gott sich setzen, wie St. Paulus sagt 2 Thess. 2. Solches thut dennoch der Türke noch Tatter nicht, wie große Feinde sie der Christen sind, sondern lassen glauben an Christum, wer da will, und nehmen leiblichen Zins und Gehorsam von den Christen.',
          'Aber der Pabst will nicht lassen glauben, sondern spricht, man solle ihm Gehorsam sein, so werde man selig. Das wollen wir nicht thun, oder drüber sterben in Gottes Namen. Das kommt alles daher, daß er jure divino der Oberste hat sollen heißen über die christliche Kirche. Darum hat er sich müssen Christo gleich und über Christum setzen, sich das Haupt, hernach einen Herrn der Kirche, zuletzt auch der ganzen Welt und schlecht einen irdischen Gott rühmen lassen, bis er auch den Engeln im Himmelreich zu gebieten sich unterstund. Und wenn man unterscheidet des Pabsts Lehre von der heiligen Schrift oder sie dagegen stellet und hält, so findet sichs, daß des Pabstes Lehre, wo sie am allerbesten ist, so ist sie aus dem kaiserlichen, heidnischen Recht genommen, und lehret weltliche Händel und Gerichte, wie seine Decretales zeugen. Darnach lehret sie Ceremonien von Kirchen, Kleidern, Speisen, Personen und des Kinderspiels, Larven- und Narrenwerks ohne Maße, aber in diesem allem gar nichts von Christo, Glauben und Gottes Geboten.',
          'Zuletzt ist nichts denn eitel Teufel, da er seine Lügen von Messen, Fegfeuer, Klösterei, eigenem Werk und Gottesdienst (welches denn das rechte Pabstthum ist) treibet, über und wider Gott, verdammet, tödtet und plaget alle Christen, so solchen seinen Greuel nicht über alles heben und ehren. Darum so wenig wir den Teufel selbst für einen Herrn oder Gott anbeten können, so wenig können wir auch seinen Apostel, den Pabst oder Endechrist, in seinem Regiment zum Haupt oder Herrn leiden. Denn Lügen und Mord, Leib und Seele zu verderben ewiglich, das ist sein päbstliche Regiment eigentlich, wie ich dasselbe in vielen Büchern beweiset habe.',
          'An diesen vier Artikeln werden sie genugsam zu verdammen haben im Concilio; denn sie nicht das geringste Gliedlein von der Artikel einem uns lassen können noch wollen; deß müssen wir gewiß sein und uns erwägen der Hoffnung, Christus, unser HErr, habe seinen Widersacher angegriffen und werde nachdrücken, beide mit seinem Geist und Zukunft. Amen.',
          'Denn im Concilio werden wir nicht vor dem Kaiser oder weltlicher Oberkeit wie zu Augsburg (der ganz ein gnädiges Ausschreiben that und in der Güte ließ die Sache verhören), sondern vor dem Pabst und dem Teufel selbst werden wir da stehen, der nichts gedenkt zu hören, sondern schlechts verdammen, morden und zur Abgötterei zu zwingen. Darum müssen wir hie nicht seine Füße küssen oder sagen: Ihr seid mein gnädiger Herr! sondern, wie im Zacharia der Engel zum Teufel sprach: Strafe dich Gott, Satan.',
        ],
      },
      {
        id: 'teil3',
        title: 'Das dritte Theil der Artikel.',
        sub: '',
        paragraphs: [
          'Folgende Stücke oder Artikel mögen wir mit Gelehrten, Vernünftigen oder unter uns selbst handeln; der Pabst und sein Reich achten derselben nicht viel, denn conscientia ist bei ihnen nichts, sondern Geld, er und Gewalt ists gar.',
        ],
      },
      {
        id: 's1',
        title: 'I.',
        sub: 'Von der Sünde.',
        paragraphs: [
          'Hie müssen wir bekennen, wie St. Paulus Röm. 5. sagt, daß die Sünde sei von Adam, dem einigen Menschen, hergekommen, durch welches Ungehorsam alle Menschen sind Sünder worden, dem Tode und dem Teufel unterworfen. Dies heißt die Erbsünde oder Hauptsünde.',
          'Solcher Sünde Früchte sind darnach die bösen Werke, so in den zehn Geboten verboten sind, als Unglaube, falscher Glaube, Abgötterei, ohne Gottesfurcht sein, Vermessenheit, Verzweifeln, Blindheit, und Summa, Gott nicht kennen oder achten; darnach lügen, bei Gottes Namen schwören, nicht beten, nicht anrufen, Gottes Wort nicht achten, Eltern ungehorsam sein, morden, Unkeuschheit, stehlen, trügen etc.',
          'Solche Erbsünde ist so gar eine tiefe böse Verderbung der Natur, daß sie keine Vernunft nicht kennet, sondern muß aus der Schrift Offenbarung geglaubt werden, Ps. 51. Röm. 5. Exod. 33. Gen. 3. Darum sind das eitel Irrthümer und Blindheit wider diesen Artikel, das die Schultheologen gelehrt haben, nämlich: Daß nach dem Erbfall Adä des Menschen natürliche Kräfte sind ganz- und unverderbt geblieben, und der Mensch habe von Natur eine rechte Vernunft und guten Willen, wie die Philosophi solches lehren.',
          'Item, daß der Mensch habe einen freien Willen, Gutes zu thun und Böses zu lassen, und wiederum, Gutes zu lassen und Böses zu thun.',
          'Item, daß der Mensch möge aus natürlichen Kräften alle Gebote Gottes thun und halten.',
          'Item, er möge aus natürlichen Kräften Gott lieben über alles und seinen Nächsten als sich selbst.',
          'Item, wenn ein Mensch thut, so viel an ihm ist, so gibt ihm Gott gewißlich seine Gnade.',
          'Item, wenn er zum Sacrament will gehen, ist nicht noth ein guter Vorsatz, Gutes zu thun, sondern sei genug, daß er nicht einen bösen Vorsatz, Sünde zu thun, habe; so gar gut ist die Natur und das Sacrament so kräftig.',
          'Es sei nicht in der Schrift gegründet, daß zum guten Werk vonnöthen sei der Heilige Geist mit seiner Gnade.',
          'Solche und dergleichen viel Stücke sind aus Unverstand und Unwissenheit beide der Sünde und Christi, unsers Heilandes, gekommen, rechte heidnische Lehre, die wir nicht leiden können. Denn wo diese Lehre recht sollte sein, so ist Christus vergeblich gestorben, weil kein Schade noch Sünde im Menschen ist, dafür er sterben müßte; oder wäre allein für den Leib, nicht für die Seele auch gestorben, weil die Seele gesund und allein der Leib des Todes ist.',
        ],
      },
      {
        id: 's2',
        title: 'II.',
        sub: 'Vom Gesetze.',
        paragraphs: [
          'Hie halten wir, daß das Gesetz gegeben sei von Gott, erstlich, der Sünde zu steuern mit Dräuen und Schrecken der Strafe und mit Verheißen und Anbieten der Gnade und Wohlthat. Aber solches alles ist der Bosheit halben, so die Sünde im Menschen gewirkt, übel gerathen. Denn eines Theils sind davon ärger worden, als die dem Gesetze feind sind, darum, daß es verbeut, was sie gern thun, und gebeut, was sie ungern thun. Derhalben, wo sie vor der Strafe können, thun sie nun mehr wider das Gesetz, denn zuvor; das sind denn die rohen, bösen Leute, die Böses thun, wo sie Stätte und Raum haben.',
          'Die andern werden blind und vermessen, lassen sich dünken, sie halten und können das Gesetz halten aus ihren Kräften, wie jetzt droben gesagt ist von den Schultheologen; daher kommen die Heuchler und falschen Heiligen.',
          'Aber das vornehmste Amt oder Kraft des Gesetzes ist, daß es die Erbsünde mit den Früchten und allem offenbare und dem Menschen zeige, wie gar tief seine Natur gefallen und grundlos verderbt ist, als dem das Gesetz sagen muß, daß er keinen Gott habe noch achte, und bete fremde Götter an, welches er zuvor und ohne das Gesetz nicht geglaubt hätte. Damit wird er erschreckt, gedemüthigt, verzagt, verzweifelt, wollte gern, daß ihm geholfen würde, und weiß nicht wo aus, fähet an, Gott feind zu werden und zu murren etc. Das heißt denn Röm. 4.: Das Gesetz erreget Zorn; und Röm. 5.: Die Sünde wird größer durchs Gesetz.',
        ],
      },
      {
        id: 's3',
        title: 'III.',
        sub: 'Von der Buße.',
        paragraphs: [
          'Solch Amt behält das neue Testament und treibets auch, wie St. Paulus Röm. 1. thut und spricht: Gottes Zorn wird vom Himmel offenbart über alle Menschen; item 3.: Alle Welt ist vor Gott schuldig; und: Kein Mensch ist vor ihm gerecht. Und Christus Joh. 16.: Der Heilige Geist wird die Welt strafen um die Sünde.',
          'Das ist nun die Donneraxt Gottes, damit er beide die offenbarlichen Sünder und falschen Heiligen in einen Haufen schlägt und läßt keinen Recht haben, treibt sie allesammt in das Schrecken und Verzagen. Das ist der Hammer; wie Jeremias spricht: Mein Wort ist ein Hammer, der die Felsen zerschmettert. Das ist nicht activa contritio, eine gemachte Reue, sondern passiva contritio, das rechte Herzeleid, Leiden und Fühlen des Todes.',
          'Und das heißt denn die rechte Buße anfahen, und muß der Mensch hie hören solch Urtheil: Es ist nichts mit euch allen, ihr seid öffentliche Sünder oder Heilige, ihr müßt alle anders werden und anders thun, weder ihr jetzt seid und thut, ihr seid, wer und wie groß, weise, mächtig und heilig, als ihr wollt, hie ist niemand fromm.',
          'Aber zu solchem Amt thut das neue Testament flugs die tröstliche Verheißung der Gnade durchs Evangelium, der man glauben solle; wie Christus spricht Marci 1.: Thut Buße und glaubet dem Evangelio; das ist, werdet und machts anders und glaubet meiner Verheißung. Und vor ihm her Johannes wird genannt ein Prediger der Buße, doch zur Vergebung der Sünden, das ist, er sollte sie alle strafen und zu Sündern machen, auf daß sie wüßten, was sie vor Gott wären, und sich erkenneten als verlorne Menschen, und also dem HErrn bereitet würden, die Gnade zu empfahen und der Sünden Vergebung von ihm gewarten und annehmen. Also sagt auch Christus Luc. am 24. selbst: Man muß in meinem Namen in alle Welt predigen Buße und Vergebung der Sünden. Wo aber das Gesetz solch sein Amt allein treibet, ohne Zuthun des Evangelii, da ist der Tod und die Hölle und muß der Mensch verzweifeln, wie Saul und Judas; wie St. Paulus sagt: Das Gesetz tödtet durch die Sünde. Wiederum gibt das Evangelium nicht einerlei Weise Trost und Vergebung, sondern durchs Wort, Sacramente und dergleichen, wie wir hören werden, auf daß die Erlösung ja reichlich sei bei Gott, wie der 130. Psalm sagt, wider die große Gefängniß der Sünden.',
          'Aber jetzt müssen wir die falsche Buße der Sophisten gegen die rechte Buße halten, damit sie beide desto baß verstanden werden.',
        ],
      },
      {
        id: 's3b',
        title: 'Von der falschen Buße der Papisten.',
        sub: '',
        paragraphs: [
          'Unmöglich ists gewesen, daß sie sollten recht von der Buße lehren, weil sie die rechten Sünden nicht erkenneten; denn (wie droben gesagt) sie halten von der Erbsünde nicht recht, sondern sagen, die natürlichen Kräfte des Menschen seien ganz und unverderbt geblieben, die Vernunft könne recht lehren und der Wille könne recht darnach thun, daß Gott gewißlich seine Gnade gibt, wenn ein Mensch thut, so viel an ihm ist, nach seinem freien Willen., Hieraus mußte nun folgen, daß sie allein die wirklichen Sünden büßten, als: böse bewilligte Gedanken (denn böse Bewegung, Lust, Reizung war nicht Sünde), böse Worte, böse Werke, die der freie Wille wohl hätte können lassen.',
          'Und zu solcher Buße setzen sie drei Theile: Reue, Beichte, Genugthun, mit solcher Vertröstung und Zusage: wo der Mensch recht reuete, beichtete, genug thäte, so hätte er damit Vergebung verdient und die Sünde vor Gott bezahlt. Weiseten also die Leute in der Buße auf Zuversicht eigener Werke.',
          'Daher kam das Wort auf der Kanzel, wenn man die gemeine Beichte dem Volke vorsprach: Friste mir, HErr Gott, mein Leben, bis ich meine Sünde Buße und mein Leben bessere.',
          'Hie war kein Christus und nichts vom Glauben gedacht, sondern man hoffte mit eigenen Werken die Sünde vor Gott zu überwinden und zu tilgen; der Meinung wurden wir auch Pfaffen und Mönche, daß wir uns selbst wider die Sünde legen wollten.',
          'Mit der Reue war es also gethan: Weil niemand alle seine Sünden konnte bedenken (sonderlich das ganze Jahr begangen), flickten sie den Pelz also: wenn die verborgenen Sünden hernach ins Gedächtniß kämen, müßte man sie auch bereuen und beichten etc.; indeß waren sie Gottes Gnade befohlen.',
          'Zudem, weil auch niemand wußte, wie groß die Reue sein sollte, damit sie ja genugsam wäre vor Gott, gaben sie solchen Trost: wer nicht könnte contritionem, das ist, Reue haben, der sollte attritionem haben, welches ich mag eine halbe oder Anfang der Reue nennen; denn sie haben selbst alles beides nicht verstanden, wissen auch noch nicht, was es gesagt sei, so wenig als ich, Solche attritio ward denn contritio gerechnet, wenn man zur Beichte ging.',
          'Und wenn sichs begab, daß etwa einer sprach, er könnte nicht reuen noch Leid haben für seine Sünden, als möchte geschehen sein in der Hurenliebe oder Rachgier etc., fragten sie, ob er denn nicht wünschte oder gern wollte, daß er Reue möchte haben? Sprach er dann: ja (denn wer wollte hie nein sagen, ohne der Teufel selbst?), so nahmen sie es für die Reue an und vergaben ihm seine Sünden auf solch sein gut Werk, Hie zogen sie St. Bernhard zum Exempel an etc.',
          'Hie siehet man, wie die blinde Vernunft tappet in Gottes Sachen und Trost sucht in eigenen Werken nach ihrem Dünkel, und an Christum oder den Glauben nicht denken kann. Wenn mans nun beim Licht besiehet, ist solche Reue ein gemachter und gedichteter Gedanke aus eigenen Kräften, ohne Glauben, ohne Erkenntniß Christi, darin zuweilen der arme Sünder, wenn er an die Lust oder Rache gedacht, lieber gelacht denn geweinet hätte, ausgenommen, die entweder mit dem Gesetze recht getroffen oder von dem Teufel vergeblich sind mit traurigem Geist geplagt gewesen; sonst ist gewiß solche Reue lauter Heuchelei gewesen und hat der Sünden Lust nicht getödtet. Denn sie mußten reuen, hätten lieber mehr gesündigt, wenn es frei gewesen wäre.',
          'Mit der Beichte stund es also: Ein jeglicher mußte alle seine Sünden erzählen (welches ein unmöglich Ding ist); das war eine große Marter. Welche er aber vergessen hatte, wurden ihm so fern vergeben, wenn sie ihm würden einfallen, daß er sie noch müßte beichten. Damit konnte er nimmer wissen, wann er rein genug gebeichtet, oder wann das Beichten einmal ein Ende haben sollte; ward gleichwohl auf seine Werke geweiset und so getröstet: je reiner er beichtete und je mehr er sich schämte und sich selbst also vor dem Priester schändete, je eher und besser er genug thäte für die Sünde; denn solche Demuth erwürbe gewißlich Gnade bei Gott.',
          'Hie war auch kein Glaube noch Christus, und die Kraft der Absolution ward ihm nicht gesagt, sondern auf Sünden zählen und schämen stund sein Trost. Es ist aber nicht zu erzählen, was Marter, Büberei und Abgötterei solch Beichten angerichtet hat.',
          'Die Genugthuung ist noch das Allerweitläuftigste; denn kein Mensch konnte wissen, wie viel er thun sollte für eine einige Sünde, schweige denn für alle. Hie fanden sie nun einen Rath, nämlich, daß sie wenig Genugthuns aufsetzten, die man wohl halten konnte, als, fünf Paternoster, einen Tag fasten etc.; mit der übrigen Buße weisete man sie ins Fegfeuer.',
          'Hie war nun auch ein eitel Jammer und Noth. Etliche meinten, sie würden nimmer aus dem Fegfeuer kommen, dieweil nach den alten Canonen sieben Jahr Buße auf eine Todsünde gehörte. Noch stund die Zuversicht auch auf unserm Werk der Genugthuung, und wo die Genugthuung hätte mögen vollkommen sein, so hätte die Zuversicht gar darauf gestanden, und wäre weder Glaube noch Christus nütze gewesen; aber sie war unmöglich. Wenn nun einer hundert Jahre also gebüßet hätte, so hätte er doch nicht gewußt, wann er ausgebüßet hätte; das hieß immerdar gebüßet, und nimmermehr zur Buße kommen.',
          'Hie kam nun der heilige Stuhl zu Rom der armen Kirche zu Hilfe und erfand den Ablaß; damit vergab und hub er auf die Genugthuung; erstlich einzeln, sieben Jahr, hundert Jahr etc., und theilte es aus unter die Cardinäle und Bischöfe, daß einer konnte hundert Jahr, einer hundert Tage Ablaß geben; aber die ganze Genugthuung aufzuheben, behielt er ihm allein zuvor.',
          'Da nun solches begann Geld zu tragen und der Bullenmarkt gut ward, erdachte er das Güldenjahr und legte es gen Rom das hieß er Vergebung aller Pein und Schuld; da liefen die Leute zu; denn es wäre jedermann gern der schweren, unträglichen Last los gewesen. Das hieß die Schätze der Erde finden und erheben. Flugs eilte der Pabst weiter und machte viel Güldenjahr auf einander; aber je mehr er Geld verschlang, je weiter ihm der Schlund ward.',
          'Darum schickte ers darnach durch Legaten heraus in die Länder, bis alle Kirchen und Häuser voll Güldenjahr wurden. Zuletzt rumpelte er auch ins Fegfeuer unter die Todten, erstlich mit Messen und Vigilien stiften, darnach mit dem Ablaß und dem Güldenjahr, und wurden endlich die Seelen so wohlfeil, daß er eine um einen Schwertgroschen losgab.',
          'Noch half das auch alles nicht, denn der Pabst, wiewohl er die Leute auf solchen Ablaß lehrte sich verlassen und vertrauen, so machte ers doch selbst wiederum auch ungewiß; denn er setzte in seine Bullen: wer des Ablasses oder Güldenjahrs wollte theilhaftig sein, der sollte bereuet und gebeichtet sein und Geld geben. Nun haben wir droben gehört, daß solche Reue und Beichte bei ihnen ungewiß und Heuchelei ist. Desgleichen wußte auch niemand, welche Seele im Fegfeuer wäre, und so etliche drinnen wären, wußte niemand, welche recht gereuet und gebeichtet hätten. Also nahm er das liebe Geld und vertröstete sie dieweil auf seine Gewalt und Ablaß und weisete sie doch wiederum auf ihr ungewiß Werk.',
          'Wo nun etliche waren, die nicht solcher wirklicher Sünden mit Gedanken, Worten und Werken sich schuldig däuchten, wie ich und meines Gleichen in Klöstern und Stiften Mönche und Pfaffen sein wollten, die wir mit Fasten, Wachen, Beten, Messe halten, harten Kleidern und Lager etc. uns wehrten wider böse Gedanken und mit Ernst und Gewalt wollten heilig sein, und doch das erbliche angeborne Uebel etwa im Schlaf that (wie auch St. Augustinus und Hieronymus mit andern bekennen), was seine Art ist, so hielt doch ein jeglicher vom andern, daß etliche so heilig wären, wie wir lehrten, die ohne Sünde, voll guter Werke wären, also, daß wir darauf unsere guten Werke andern, als uns überflüssig zum Himmel, mittheilten und verkauften. Das ist ja wahr und sind Siegel, Briefe und Exempel vorhanden, Diese bedurften der Buße nicht, Denn was wollten sie bereuen, weil sie in böse Gedanken nicht bewilligten? Was wollten sie beichten, weil sie Worte vermieden? Wofür wollten sie genug thun, weil sie der That unschuldig waren, also, daß sie auch andern armen Sündern ihre übrige Gerechtigkeit verkaufen konnten? Solche Heilige waren auch die Pharisäer und Schriftgelehrten zur Zeit Christi.',
          'Hie kommt der feurige Engel St. Johannes, der rechte Bußprediger, und schlägt mit einem Donner alle beide in einen Haufen, spricht: Thut Buße. So denken jene: Haben wir doch gebüßet; diese denken: Wir bedürfen keiner Buße. Spricht Johannes: Thut alle beide Buße, denn ihr seid falsche Büßer, so sind diese falsche Heilige, und bedürft alle beide Vergebung der Sünden, weil ihr alle beide noch nicht wisset, was die rechte Sünde sei, schweige, daß ihr sie büßen oder meiden solltet. Es ist euer keiner gut, seid voller Unglaubens, Unverstands und Unwissenheit Gottes und seines Willens. Denn da ist er vorhanden, von des Fülle wir alle müssen nehmen Gnade um Gnade; und kein Mensch ohne ihn vor Gott kann gerecht sein. Darum wollt ihr büßen, so büßet recht; eure Buße thuts nicht. Und ihr Heuchler, die ihr keiner Buße bedürft, ihr Schlangengeziefer, wer hat euch versichert, daß ihr dem künftigen Zorn entrinnen werdet? etc.',
          'Also predigt auch St. Paulus Röm. 3. und spricht: Es ist keiner verständig, keiner gerecht, keiner achtet Gottes, keiner thut Gutes, auch nicht einer; allzumal sind sie untüchtig und abtrünnig. Und Act. 17.: Nun aber gebeut Gott allen Menschen an allen Enden Buße zu thun. Allen Menschen, spricht er, niemand ausgenommen, der ein Mensch ist. Diese Buße lehrt uns die Sünde erkennen, nämlich, daß es mit uns allen verloren, Haut und Haar nicht gut ist, und müssen schlechts neue und andere Menschen werden.',
          'Diese Buße ist nicht stücklich und bettelisch, wie jene, so die wirklichen Sünden büßet, und ist auch nicht ungewiß, wie jene; denn sie disputirt nicht, welches Sünde oder nicht Sünde sei, sondern stößt alles in Haufen, spricht, es sei alles und eitel Sünde mit uns. Was wollen wir lange suchen, theilen und unterscheiden? Darum so ist auch hie die Reue nicht ungewiß. Denn es bleibet nichts da, damit wir möchten etwas Gutes gedenken, die Sünde zu bezahlen, sondern ein bloß, gewiß Verzagen an allem, das wir sind, gedenken, reden oder thun etc.',
          'Desgleichen kann die Beichte auch nicht falsch, ungewiß oder stücklich sein; denn wer bekennet, daß alles mit ihm eitel Sünde sei, der begreift alle Sünden, läßt keine außen und vergißt auch keine. Also kann die Genugthuung auch nicht ungewiß sein, denn sie ist nicht unsere ungewissen, sündlichen Werke, sondern das Leiden und Blut des unschuldigen Lämmleins Gottes, das der Welt Sünde trägt.',
          'Von dieser Buße predigt Johannes und hernach Christus im Evangelio, und wir auch. Mit dieser Buße stoßen wir Pabst und alles, was auf unsere guten Werke gebauet ist, zu Boden. Denn es ist alles auf einen faulen, nichtigen Grund gebauet, welcher heißt gute Werke oder Gesetze; so doch kein gut Werk da ist, sondern eitel böse Werke; und niemand das Gesch thut (wie Christus Joh. 7. sagt), sondern allzumal übertreten. Darum ist das Gebäu eitel Lüge und Heuchelei, wo es am allerheiligsten und allerschönsten ist.',
          'Und diese Buße währt bei den Christen bis in den Tod; denn sie beißt sich mit der übrigen Sünde im Fleisch durchs ganze Leben, wie St. Paulus Röm. 7. zeuget, daß er kämpfe mit dem Gesetze seiner Glieder etc., und das nicht durch eigene Kräfte, sondern durch die Gabe des Heiligen Geistes, welche folget auf die Vergebung der Sünden. Dieselbige Gabe reinigt und fegt täglich die übrigen Sünden aus und arbeitet, den Menschen recht rein und heilig zu machen.',
          'Hievon weiß Pabst, Theologen, Juristen noch kein Mensch nichts, sondern ist eine Lehre vom Himmel, durchs Evangelium offenbart, und muß Ketzerei heißen bei den gottlosen Heiligen.',
          'Wiederum ob etliche Rottengeister kommen würden, wie vielleicht etliche bereits da vorhanden sind und zur Zeit der Aufruhr mir selbst vor Augen kamen, die da halten, daß alle die, so einmal den Geist oder Vergebung der Sünden empfangen hätten oder gläubig worden wären, wenn dieselbigen hernach sündigten, so blieben sie gleichwohl im Glauben und schadete ihnen solche Sünde nicht; und schrieen also: Thu, was du willst, glaubst du, so ists alles nichts, der Glaube vertilgt alle Sünden etc.; sagen dazu: Wo jemand nach dem Glauben und Geist sündigte, so habe er den Geist und Glauben nie recht gehabt. Solcher unsinnigen Menschen habe ich viel vor mir gehabt, und sorge, daß noch in etlichen solcher Teufel stecke, Darum so ist vonnöthen zu wissen und zu lehren, daß, wo die heiligen Leute über das, so sie die Erbsünde noch haben und fühlen, dawider auch täglich büßen und streiten, etwa in öffentliche Sünde fallen, als David in Ehebruch, Mord und Gotteslästerung, daß alsdann der Glaube und Geist ist weg gewesen. Denn der Heilige Geist läßt die Sünde nicht walten und überhand gewinnen, daß sie vollbracht werde, sondern steuert und wehret, daß sie nicht muß thun, was sie will; thut sie aber, was sie will, so ist der Heilige Geist und Glaube nicht dabei; denn es heißt, wie St. Johannes sagt: Wer aus Gott geboren ist, der sündigt nicht, und kann nicht sündigen. Und ist doch auch die Wahrheit, wie derselbige St. Johannes schreibt: So wir sagen, daß wir nicht Sünde haben, so lügen wir, und Gottes Wahrheit ist nicht in uns.',
        ],
      },
      {
        id: 's4',
        title: 'IV.',
        sub: 'Vom Evangelio.',
        paragraphs: [
          'Wir wollen nun wieder zum Evangelio kommen, welches gibt nicht einerlei Weise, Rath und Hilfe wider die Sünde; denn Gott ist überschwänglich reich in seiner Gnade: erstlich durchs mündliche Wort, darin gepredigt wird Vergebung der Sünden in aller Welt, welches ist das eigentliche Amt des Evangelii; zum andern, durch die Taufe; zum dritten, durchs heilige Sacrament des Altars; zum vierten, durch die Kraft der Schlüssel, und auch per mutuum colloquium et consolationem fratrum, Matth. 18.: Ubi duo fuerint congregati etc.',
        ],
      },
      {
        id: 's5',
        title: 'V.',
        sub: 'Von der Taufe.',
        paragraphs: [
          'Die Taufe ist nichts anders denn Gottes Wort im Wasser, durch seine Einsetzung befohlen, oder, wie St. Paulus sagt Eph. 5.: lavacrum in verbo; wie auch Augustinus sagt: Accedat verbum ad elementum, et fit sacramentum, Und darum halten wirs nicht mit Thomas und den Predigermönchen, die des Worts (Gottes Einsetzung) vergessen, und sagen, Gott habe eine geistliche Kraft ins Wasser gelegt, welche die Sünde durchs Wasser abwasche; auch nicht mit Scoto und den Barfüßermönchen, die da lehren, daß die Taufe die Sünde abwasche aus Beistehen göttliches Willens, also, daß diese Abwaschung geschieht allein durch Gottes Willen, gar nicht durchs Wort oder Wasser.',
          'Von der Kindertaufe halten wir, daß man die Kinder taufen solle; denn sie gehören auch zu der verheißenen Erlösung, durch Christum geschehen, und die Kirche soll sie ihnen reichen.',
        ],
      },
      {
        id: 's6',
        title: 'VI.',
        sub: 'Vom Sacrament des Altars.',
        paragraphs: [
          'Vom Sacrament des Altars halten wir, daß Brot und Wein im Abendmahl sei der wahrhaftige Leib und Blut Christi, und werde nicht allein gereicht und empfangen von frommen, sondern auch von bösen Christen.',
          'Und daß man nicht soll einerlei Gestalt allein geben. Und wir bedürfen der hohen Kunst nicht, die uns lehre, daß unter einer Gestalt so viel sei als unter beiden, wie uns die Sophisten und das Concilium zu Constanz lehren. Denn obs gleich wahr wäre, daß unter einer so viel sei, als unter beiden, so ist doch die einige Gestalt nicht die ganze Ordnung und Einsetzung, durch Christum gestiftet und befohlen. Und sonderlich verdammen und verfluchen wir in Gottes Namen diejenigen, so nicht allein beide Gestalt lassen anstehen, sondern auch gar herrlich daher verbieten, verdammen, lästern als Ketzerei, und setzen sich damit wider und über Christum, unsern HErrn und Gott etc.',
          'Von der Transsubstantiation achten wir der spitzigen Sophisterei gar nichts, da sie lehren, daß Brot und Wein verlassen oder verlieren ihr natürlich Wesen, und bleibe allein Gestalt und Farbe des Brots, und nicht recht Brot. Denn es reimet sich mit der Schrift aufs beste, daß Brot da sei und bleibe, wie es St. Paulus selbst nennet: Das Brot, das wir brechen; und: Also esse er von dem Brot.',
        ],
      },
      {
        id: 's7',
        title: 'VII.',
        sub: 'Von den Schlüsseln.',
        paragraphs: [
          'Die Schlüssel sind ein Amt und Gewalt der Kirche von Christo gegeben, zu binden und zu lösen die Sünden, nicht allein die groben und wohl bekannten Sünden, sondern auch die subtilen, heimlichen, die Gott allein erkennet. Wie geschrieben steht im 19. Psalm: Wer kennet, wie viel er fehlet? Und St. Paulus Röm. 7. klagt selbst, daß er mit dem Fleisch diene dem Gesetze der Sünden. Denn es stehet nicht bei uns, sondern bei Gott allein, zu urtheilen, welche, wie groß und wie viel Sünden sind, wie geschrieben stehet im 143. Psalm: Gehe nicht ins Gericht mit deinem Knecht, denn vor dir ist kein lebendiger Mensch gerecht. Und Paulus 1 Cor. 4. auch sagt: Ich bin mir wohl nichts bewußt, aber darum bin ich nicht gerecht.',
        ],
      },
      {
        id: 's8',
        title: 'VIII.',
        sub: 'Von der Beichte.',
        paragraphs: [
          'Weil die Absolutio oder Kraft des Schlüssels auch eine Hilfe und Trost ist wider die Sünde und böses Gewissen, im Evangelio durch Christum gestiftet, so soll man die Beichte oder Absolution bei Leibe nicht lassen abkommen in der Kirche, sonderlich um der blöden Gewissen willen, auch um des jungen rohen Volks willen, damit es verhört und unterrichtet werde in der christlichen Lehre.',
          'Die Erzählung aber der Sünden soll frei sein einem jeden, was er erzählen oder nicht erzählen will; denn so lange wir im Fleisch sind, werden wir nicht lügen, wenn wir sagen: Ich bin ein armer Mensch voller Sünden; Röm. 7.: Ich fühle ein ander Gesetz in meinen Gliedern etc. Denn dieweil die absolutio privata von dem Amt herkommt der Schlüssel, soll man sie nicht verachten, sondern hoch und werth halten, wie alle anderen Aemter der christlichen Kirche.',
          'Und in diesen Stücken, so das mündliche, äußerliche Wort betreffen, ist fest darauf zu bleiben, daß Gott niemand seinen Geist oder Gnade gibt, ohne durch oder mit dem vorgehenden äußerlichen Wort. Damit wir uns bewahren vor den Enthusiasten, das ist, Geistern, so sich rühmen, ohne und vor dem Wort den Geist zu haben, und darnach die Schrift oder mündlich Wort richten, deuten und dehnen ihres Gefallens; wie der Münzer that und noch viel thun heutiges Tages, die zwischen dem Geist und Buchstaben scharfe Richter sein wollen, und wissen nicht, was sie sagen oder setzen. Denn das Pabstthum auch ein eitel Enthusiasmus ist, darin der Pabst rühmet, alle Rechte sind im Schrein seines Herzens, und was er mit seiner Kirche urtheilt und heißt, das soll Geist und Recht sein, wenns gleich über und wider die Schrift oder das mündliche Wort ist.',
          'Das ist alles der alte Teufel und alte Schlange, der Adam und Heva auch zu Enthusiasten machte, vom äußerlichen Wort Gottes auf Geisterei und Eigendünkel führte, und thats doch auch durch andere äußerliche Worte. Gleichwie auch unsere Enthusiasten das äußerliche Wort verdammen, und doch sie selbst nicht schweigen, sondern die Welt voll plaudern und schreiben, gerade als könnte der Geist durch die Schrift oder mündlich Wort der Apostel nicht kommen, aber durch ihre Schrift und Wort müßte er kommen. Warum lassen sie auch ihre Predigt und Schrift nicht anstehen, bis der Geist selber in die Leute ohne und vor ihrer Schrift kommt, wie sie rühmen, daß er in sie gekommen sei ohne Predigt der Schrift? Davon hie weiter nicht Zeit ist zu disputiren; wir habens sonst genugsam getrieben.',
          'Denn auch die, so vor der Taufe glauben oder in der Taufe gläubig werden, habens durchs äußerliche vorgehende Wort, als, die Alten, so zu Vernunft gekommen sind, müssen zuvor gehört haben, daß, wer da glaubt und getauft wird, der ist selig, ob sie gleich, erst ungläubig, nach zehn Jahren den Geist und Taufe kriegen. Und Cornelius Act. am 10. hatte lange zuvor gehöret bei den Juden vom künftigen Messias, dadurch er gerecht vor Gott und sein Gebet und Almosen angenehm waren in solchem Glauben (wie Lucas ihn gerecht und gottfürchtig nennet), und nicht ohne solch vorgehendes Wort oder Gehör konnte glauben noch gerecht sein. Aber St. Petrus mußte ihm offenbaren, daß der Messias (an welchen zukünftigen er bis daher geglaubt hatte) nun gekommen wäre, und sein Glaube vom zukünftigen Messias ihn nicht bei den verstockten, ungläubigen Juden gefangen hielte, sondern wüßte, daß er nun müßte selig werden durch den gegenwärtigen Messiam, und denselben nicht mit den Juden verleugnen noch verfolgen etc.',
          'Summa, der Enthusiasmus steckt in Adam und seinen Kindern von Anfang bis zum Ende der Welt, von dem alten Drachen in sie gestiftet und gegiftet, und ist aller Ketzerei, auch des Pabstthums und Mahomets Ursprung, Kraft und Macht. Darum sollen und müssen wir darauf beharren, daß Gott nicht will mit uns Menschen handeln, denn durch sein äußerlich Wort und Sacrament. Alles aber, was ohne solch Wort und Sacrament vom Geist gerühmet wird, das ist der Teufel. Denn Gott wollte auch Mosi erstlich durch den feurigen Busch und mündlich Wort erscheinen, und kein Prophet, weder Elias noch Elisäus, außer oder ohne die zehn Gebote den Geist gekriegt haben. Und Johannes der Täufer nicht ohne Gabriels vorgehendes Wort empfangen, noch ohne Mariä Stimme in seiner Mutter Leibe sprang. Und St. Petrus spricht: Die Propheten haben nicht aus menschlichem Willen, sondern aus dem Heiligen Geist geweissagt, doch als die heiligen Menschen Gottes. Aber ohne äußerlich Wort waren sie nicht heilig, viel weniger hätte sie als noch Unheilige der Heilige Geist zu reden getrieben; denn sie waren heilig, spricht er, da der Heilige Geist durch sie redete.',
        ],
      },
      {
        id: 's9',
        title: 'IX.',
        sub: 'Vom Bann.',
        paragraphs: [
          'Den großen Bann, wie es der Pabst nennet, halten wir für eine lauter weltliche Strafe und geht uns Kirchendiener nichts an. Aber der kleine, das ist, der rechte christliche Bann ist, daß man offenbarliche, halsstarrige Sünder nicht soll lassen zum Sacrament oder anderer Gemeinschaft der Kirche kommen, bis sie sich bessern und die Sünde meiden. Und die Prediger sollen in diese geistliche Strafe oder Bann nicht mengen die weltliche Strafe.',
        ],
      },
      {
        id: 's10',
        title: 'X.',
        sub: 'Von der Weihe und Vocation.',
        paragraphs: [
          'Wenn die Bischöfe wollten rechte Bischöfe sein, und sich der Kirche und des Evangelii annehmen, so möchte man ihnen das um der Liebe und Einigkeit willen, doch nicht aus Noth, lassen gegeben sein, daß sie uns und unsere Prediger ordinirten und confirmirten; doch hintangesetzt alle Larven und Gespenste unchristliches Wesens und Gepränges. Nun sie aber nicht rechte Bischöfe sind oder auch nicht sein wollen, sondern weltliche Herren und Fürsten, die weder predigen, noch lehren, noch taufen, noch communiciren, noch einiges Werk oder Amt der Kirche treiben wollen, dazu diejenigen, die solch Amt berufen treiben, verfolgen und verdammen, so muß dennoch um ihretwillen die Kirche nicht ohne Diener bleiben.',
          'Darum, wie die alten Exempel der Kirche und der Väter uns lehren, wollen und sollen wir selbst ordiniren tüchtige Personen zu solchem Amt. Und das haben sie uns nicht zu verbieten noch zu wehren, auch nach ihrem eigenen Rechte. Denn ihre Rechte sagen, daß diejenigen, so auch von Ketzern ordinirt sind, sollen geordinirt heißen und bleiben. Gleichwie St. Hieronymus schreibt von der Kirche zu Alexandria, daß sie erstlich ohne Bischöfe, durch die Priester und Prediger ingemein regiert sind worden.',
        ],
      },
      {
        id: 's11',
        title: 'XI.',
        sub: 'Von der Priester Ehe.',
        paragraphs: [
          'Daß sie die Ehe verboten und den göttlichen Stand der Priester mit ewiger Keuschheit beschweret haben, das haben sie weder Fug noch Recht gehabt, sondern haben gehandelt als die endechristischen, tyrannischen, verzweifelten Buben; und damit Ursache gegeben allerlei erschrecklicher, greulicher, unzähliger Sünden der Unkeuschheit, darinnen sie denn noch stecken. Als wenig nun uns oder ihnen Macht gegeben ist, aus einem Männlein ein Fräulein, oder aus einem Fräulein ein Männlein zu machen, oder beides nichts zu machen, so wenig haben sie auch Macht gehabt, solche Kreatur Gottes zu scheiden, oder verbieten, daß sie nicht ehrlich und ehelich bei einander sollten wohnen. Darum wollen wir in ihren leidigen Cölibat nicht willigen, auch nicht leiden, sondern die Ehe frei haben, wie sie Gott geordnet und gestiftet hat; und wollen sein Werk nicht zerreißen noch hindern; denn St. Paulus sagt 1 Tim. 4., es sei eine teuflische Lehre.',
        ],
      },
      {
        id: 's12',
        title: 'XII.',
        sub: 'Von der Kirche.',
        paragraphs: [
          'Wir gestehen ihnen nicht, daß sie die Kirche seien, und sinds auch nicht, und wollens auch nicht hören, was sie unter dem Namen der Kirche gebieten oder verbieten. Denn es weiß, Gott Lob, ein Kind von sieben Jahren, was die Kirche sei, nämlich die heiligen Gläubigen und die Schäflein, die ihres Hirten Stimme hören. Denn also beten die Kinder: Ich glaube eine heilige, christliche Kirche. Diese Heiligkeit stehet nicht in Chorhemden, Platten, langen Röcken und andern ihren Ceremonien, durch sie über die heilige Schrift erdichtet, sondern im Wort Gottes und rechtem Glauben.',
        ],
      },
      {
        id: 's13',
        title: 'XIII.',
        sub: 'Wie man vor Gott gerecht wird, und von guten Werken.',
        paragraphs: [
          'Was ich davon bisher und stetiglich gelehrt habe, das weiß ich gar nicht zu ändern, nämlich daß wir durch den Glauben (wie St. Petrus sagt) ein ander neu rein Herz kriegen, und Gott um Christus willen, unsers Mittlers, uns für ganz gerecht und heilig halten will und hält; ob wohl die Sünde im Fleisch noch nicht gar weg oder todt ist, so will er sie doch nicht rechnen noch wissen.',
          'Und auf solchen Glauben, Verneuerung und Vergebung der Sünden folgen dann gute Werke. Und was an demselben auch noch sündlich oder Mangel ist, soll nicht für Sünde oder Mangel gerechnet werden, eben um desselben Christi willen; sondern der Mensch soll ganz, beide nach der Person und seinen Werken, gerecht und heilig heißen und sein, aus lauter Gnade und Barmherzigkeit in Christo, über uns ausgeschüttet und ausgebreitet. Darum können wir nicht rühmen viel Verdienst unserer Werke, wo sie ohne Gnade und Barmherzigkeit angesehen werden, sondern wie geschrieben stehet 1 Cor. 1.: Wer sich rühmet, der rühme sich des HErrn, das ist, daß er einen gnädigen Gott hat; so ists alles gut. Sagen auch weiter, daß, wo gute Werke nicht folgen, so ist der Glaube falsch und nicht recht.',
        ],
      },
      {
        id: 's14',
        title: 'XIV.',
        sub: 'Von Klostergelübden.',
        paragraphs: [
          'Weil die Klostergelübde stracks wider den ersten Hauptartikel streiten, so sollen sie schlecht abe sein. Denn sie sinds, da Christus von sagt Matth. am 24.: Ego sum Christus etc. Denn wer da gelobet ein Klosterleben, der glaubt, daß er ein besser Leben führe, denn der gemeine Christenmann, und will durch seine Werke nicht allein ihm selber, sondern auch andern zum Himmel helfen; das heißt Christum verleugnen. Und sie rühmen aus ihrem St. Thomas, daß Klostergelübde der Taufe gleich sei; das ist eine Gotteslästerung.',
        ],
      },
      {
        id: 's15',
        title: 'XV.',
        sub: 'Von Menschensatzungen.',
        paragraphs: [
          'Daß die Papisten sagen, Menschensatzungen dienen zu Vergebung der Sünden oder verdienen die Seligkeit, das ist unchristlich und verdammt, wie Christus spricht: Vergeblich dienen sie mir, weil sie lehren solche Lehren, die nichts sind denn Menschengebote. Item ad Titum 1.: Aversantium veritatem. Item, daß sie sagen, es sei Todsünde, solche Satzungen brechen, ist auch nicht recht.',
          'Dies sind die Artikel, darauf ich stehen muß und stehen will bis in meinen Tod, ob Gott will, und weiß darinnen nichts zu ändern noch nachzugeben; will aber jemand etwas nachgeben, das thue er auf sein Gewissen.',
          'Zuletzt ist noch der Gaukelsack des Pabsts dahinten von närrischen und kindischen Artikeln, als von Kirchweihe, von Glockentaufen, Altarsteintaufen und Gevattern dazu bitten, die dazu gaben etc. Welches Taufen ein Spott und Hohn der heiligen Taufe ist, daß mans nicht leiden soll.',
          'Darnach von Licht weihen, Palmen, Fladen, Hafer, Würz weihen etc.; welches doch nicht kann geweihet heißen noch sein, sondern eitel Spott und Betrug ist. Und des Gaukelwerks unzählig viel, welche wir befehlen ihrem Gott und ihnen selbst anzubeten, bis sie es müde werden; wir wollen damit unverworren sein.',
        ],
      },
      {
        id: 'unterschriften',
        title: 'Unterschriften.',
        sub: '',
        paragraphs: [
          'Martinus Luther D. subscripsit.',
          'Justus Jonas D. Rector, subscripsit manu propria.',
          'Johannes Bugenhagen Pomer. D. subscripsit.',
          'Caspar Creutziger D. subscripsit.',
          'Niclas Amsdorff subscripsit Magdeburgensis.',
          'Georgius Spalatinus subscripsit Aldenburgensis.',
          'Ich Philippus Melanchthon halte diese obgestalte Artikel auch für recht und christlich. Vom Pabst aber halte ich, so er das Evangelium wollte zulassen, daß ihm um Friedens und gemeiner Einigkeit willen derjenigen Christen, so auch unter ihm sind und künftig sein möchten, seine Superiorität über die Bischöfe, die er sonst hat, jure humano auch von uns zugelassen sei.',
        ],
      },
    ],
  },
];
